Merlin: merlin::graphical_model Class Reference
merlin::graphical_model Class Reference
Graphical model base class.
#include <graphical_model.h>
Public Types
typedef size_t findex
Factor index.
typedef size_t vindex
Variable index.
typedef set< findex > flist
Collection of factor indices.
Public Types inherited from merlin::graph
typedef edge_id::index index
Basic indexing type for the graph.
Public Member Functions
graphical_model ()
Creates an empty graphical model.
graphical_model (const graphical_model &gm)
Creates a graphical model by copying an existing one.
graphical_model & operator= (const graphical_model &gm)
Assignment operator (deep copy).
virtual graphical_model * clone ()
Clone the graphical model.
graphical_model (std::vector< factor > fs)
Constructor from a list of factors.
template<class InputIterator >
graphical_model (InputIterator first, InputIterator last)
Creates a graphical model from input iterators.
virtual ~graphical_model ()
Destroys the graphical model.
void read (const char *file_name)
Read the graphical model from a file in the UAI format.
void write (const char *file_name)
Write the graphical model to a file using the UAI format.
bool is_markov ()
Check if graphical model is a Markov or a Bayes net.
std::vector< factor > assert_evidence (const char *file_name, std::map< size_t, size_t > &evidence, std::map< size_t, size_t > &old_to_new)
Assert evidence into the graphical model.
std::vector< factor > assert_evidence (const std::map< size_t, size_t > &evidence, std::map< size_t, size_t > &old_to_new)
Assert evidence into the graphical model.
size_t nvar () const
Return the number of variables in the model.
variable var (vindex i) const
Convert a variable index to Var object.
size_t num_factors () const
Return the number of factors in the model.
const factor & get_factor (findex idx) const
Accessor for a factor.
const std::vector< factor > & get_factors () const
Accessor for the factor container.
const flist & with_variable (const variable &v) const
Factors depending on a variable.
flist with_variable_set (const variable_set &vs) const
Union of factors depending on a set of variables.
flist intersects (const variable_set &vs) const
Intersection of factors depending on a set of variables.
flist contains (const variable &v) const
Factors depending on a variable.
flist contains (const variable_set &vs) const
Union of factors depending on a set of variables.
flist contained_by (const variable_set &vs) const
Factors contained by a set of variables.
variable_set markov_blanket (const variable &v) const
Markov blanket of a variable.
variable_set markov_blanket (const variable_set &vs) const
Markov blanket of a set of variables.
std::vector< variable_set > mrf () const
Full adjacency matrix.
virtual findex add_factor (const factor &F)
Add a new factor to the model.
virtual void remove_factor (findex idx)
Remove a factor from the model.
void clear_factors ()
Remove all factors.
findex smallest (const flist &fl)
Find the factor with the smallest scope.
findex largest (const flist &fl)
Find the factor with the largest scope.
bool is_binary () const
Check if a binary model.
bool is_pairwise () const
Check if a pairwise model.
factor joint (size_t maxsize=0) const
Directly calculate joint distribution function.
size_t induced_width (const variable_order_t &order) const
Find the induced width (complexity) of an elimination order.
std::pair< size_t, size_t > pseudo_tree_size (const variable_order_t &order) const
Find induced width and pseudo tree height of an elimination order.
std::vector< vindex > pseudo_tree (const variable_order_t &order) const
Find the pseudo tree corresponding to an elimination order.
MER_ENUM (OrderMethod, MinFill, WtMinFill, MinWidth, WtMinWidth, Random)
Variable ordering methods.
variable_order_t order (OrderMethod ord_type) const
Find a variable elimination order.
variable_order_t order2 (OrderMethod ord_type) const
Find a variable elimination order.
variable_order_t order2 (OrderMethod ord_type, std::vector< bool > var_types) const
Find a constrained variable elimination order.
variable_order_t order (OrderMethod ord_type, std::vector< bool > var_types) const
Find a constrained variable elimination order.
void improve_order (OrderMethod ord_type, double &old_score, variable_order_t &old_order) const
Look for a better order iteratively.
void insert (std::vector< flist > &adj, findex idx, const variable_set &vs)
Add the scope of a factor to the adjacency list.
void erase (std::vector< flist > &adj, findex idx, const variable_set &vs)
Remove the scope of a factor from the adjacency list.
std::vector< size_t > max_simple ()
Find smallest factor with each variable and select its optimum.
std::vector< size_t > max_sequential (const variable_order_t &order)
Find maxmarginal for variable and select optimum given those so far.
double logP (const std::vector< size_t > &config)
Compute the log-probability of a particular (complete) configuration.
double get_global_const () const
Return the constant resulted from asserting evidence in the model.
Public Member Functions inherited from merlin::graph
graph (size_t n=0)
Constructs a graph with n vertices and 0 edges.
~graph ()
Destroys the graph.
index add_node ()
Add a node to the graph.
void remove_node (index i)
Remove a node from the graph.
size_t num_nodes ()
Return the number of nodes.
size_t num_edges ()
Return the number of edges.
const edge_id & add_edge (index i, index j)
Add an edge to the graph.
void remove_edge (index i, index j)
Remove an edge from the graph.
void clear ()
Clear the graph by removing all nodes and edges.
void clear_edges ()
Remove all edges.
const edge_id & edge (index i, index j) const
Return the edge (if any) between two nodes.
const set< edge_id > & neighbors (index i) const
Return the neighbors of a node (ie, adjacency list).
const edge_id & edge (index eij) const
Return an edge (by its index).
const std::vector< edge_id > & edges () const
Return the edges of the graph.
Protected Member Functions
size_t _vindex (const variable &v) const
Look up the index of a variable.
flist & _with_variable (const variable &v)
Mutable accessor of adjacency.
void fixup ()
Internal function for ensuring consistency of the model.
double order_score (const std::vector< variable_set > &adj, size_t i, OrderMethod kOType) const
Compute the score of a variable for the elimination order.
variable_order_t order_random () const
Create a random elimination order.
Protected Attributes
std::vector< factor > m_factors
Collection of all factors in the model.
bool m_markov
Markov or Bayes network. Default is true (Markov)
Protected Attributes inherited from merlin::graph
std::stack< index > m_vvacant
List of available vertex ids.
std::stack< index > m_evacant
List of available edge ids.
Friends
std::ostream & operator<< (std::ostream &out, const graphical_model &gm)
Output operator.
Additional Inherited Members
Public Attributes inherited from merlin::graph
std::vector< set< edge_id > > m_adj
Look up EdgeID info by adj[i][jj] (jj = position of j).
std::vector< edge_id > m_edges
Look up EdgeID info by edges[eij] (edge index).
Detailed Description
Graphical model base class.
Simplest form of a graphical model, namely just a collection of variables and factors (defined on subsets of variables). Internally, factors and variables are mainly referenced by integer indices, with 0 <= f < nFactors() and 0 <= v < nvar(). However, many interface functions are called using a variable object, Var(label,dim). To convert, var(v) gives the vth Var object and the internal function _vindex(V) gives the index corresponding to variable object V.
Definition at line 47 of file graphical_model.h.
Constructor & Destructor Documentation
merlin::graphical_model::graphical_model (const graphical_model & gm) inline
Creates a graphical model by copying an existing one.
Parameters
gm An object of the same type
Definition at line 69 of file graphical_model.h.
merlin::graphical_model::graphical_model (std::vector< factor > fs) inline
Constructor from a list of factors.
Parameters
fs The list of factors
Definition at line 102 of file graphical_model.h.
References fixup().
template<class InputIterator > merlin::graphical_model::graphical_model (InputIterator first, InputIterator last) inline
Creates a graphical model from input iterators.
Parameters
first The iterator to beginning
last The iterator to end
Definition at line 113 of file graphical_model.h.
References fixup().
Member Function Documentation
size_t merlin::graphical_model::_vindex (const variable & v) const inline protected
Look up the index of a variable.
Parameters
v The variable object
Returns
the index corresponding to the variable in the model.
Definition at line 1441 of file graphical_model.h.
References merlin::variable::label().
Referenced by _with_variable(), add_factor(), merlin::factor_graph::create_factor_graph(), fixup(), improve_order(), induced_width(), merlin::factor_graph::local_factor(), order(), order2(), order_score(), pseudo_tree(), pseudo_tree_size(), merlin::factor_graph::remove_factor(), merlin::factor_graph::span_tree(), and with_variable().
flist& merlin::graphical_model::_with_variable (const variable & v) inline protected
Mutable accessor of adjacency.
Parameters
v The variable object
Returns
the list of factors containing the variable in their scope.
Definition at line 1450 of file graphical_model.h.
References _vindex().
Referenced by fixup().
virtual findex merlin::graphical_model::add_factor (const factor & F) inline virtual
Add a new factor to the model.
Parameters
F The factor to be added
Returns
the index associated with the newly added factor.
Reimplemented in merlin::factor_graph.
Definition at line 562 of file graphical_model.h.
References _vindex(), merlin::graph::add_node(), merlin::variable_set::begin(), merlin::variable_set::end(), insert(), m_factors, num_factors(), and merlin::factor::vars().
Referenced by merlin::factor_graph::add_factor(), merlin::factor_graph::create_factor_graph(), merlin::bte::init(), merlin::ijgp::init(), merlin::wmb::init(), and merlin::jglp::run().
std::vector<factor> merlin::graphical_model::assert_evidence (const char * file_name, std::map< size_t, size_t > & evidence, std::map< size_t, size_t > & old_to_new) inline
Assert evidence into the graphical model.
Parameters
[in] file_name The full path to a file containing the evidence
[out] evidence The map containing evidence variable value pairs
[out] old_to_new The mappings between old and new variable indexes
Returns
the list of new factors resulting from conditioning on the evidence.
Definition at line 272 of file graphical_model.h.
References merlin::variable_set::begin(), merlin::factor::condition(), merlin::variable_set::contains(), merlin::variable_set::end(), merlin::factor::isscalar(), m_factors, merlin::factor::table(), var(), and merlin::factor::vars().
Referenced by Merlin::run().
std::vector<factor> merlin::graphical_model::assert_evidence (const std::map< size_t, size_t > & evidence, std::map< size_t, size_t > & old_to_new) inline
Assert evidence into the graphical model.
Parameters
[in] evidence The map containing evidence variable value pairs
[out] old_to_new The mappings between old and new variable indexes
Returns
the list of new factors resulting from conditioning on the evidence.
Definition at line 345 of file graphical_model.h.
References merlin::variable_set::begin(), merlin::factor::condition(), merlin::variable_set::contains(), merlin::variable_set::end(), merlin::factor::isscalar(), m_factors, merlin::variable::states(), merlin::factor::table(), var(), and merlin::factor::vars().
virtual graphical_model* merlin::graphical_model::clone () inline virtual
Clone the graphical model.
Returns
the pointer to the new object representing the copy of the current model.
Reimplemented in merlin::factor_graph.
Definition at line 93 of file graphical_model.h.
References graphical_model().
Referenced by Merlin::read_model().
flist merlin::graphical_model::contained_by (const variable_set & vs) const inline
Factors contained by a set of variables.
Parameters
vs The set of variables
Returns
the list of factor indexes contained by the set of variables.
Definition at line 508 of file graphical_model.h.
References intersects(), m_factors, and merlin::set< T >::size().
flist merlin::graphical_model::contains (const variable & v) const inline
Factors depending on a variable.
Parameters
v The variable object
Returns
the list of factor indexes containing the variable in their scopes.
Definition at line 490 of file graphical_model.h.
References with_variable().
Referenced by merlin::bte::update(), merlin::ijgp::update(), and merlin::wmb::update().
flist merlin::graphical_model::contains (const variable_set & vs) const inline
Union of factors depending on a set of variables.
Parameters
vs The set of variable object
Returns
the list of factor indexes containing those variables in their scopes.
Definition at line 499 of file graphical_model.h.
References with_variable_set().
void merlin::graphical_model::erase (std::vector< flist > & adj, findex idx, const variable_set & vs) inline
Remove the scope of a factor from the adjacency list.
Parameters
adj The adjacency list to be modified
idx The index of the factor
vs The scope of the factor
Definition at line 1360 of file graphical_model.h.
References merlin::variable_set::nvar().
Referenced by merlin::jglp::config(), merlin::bte::init(), merlin::ijgp::init(), merlin::wmb::init(), and remove_factor().
const factor& merlin::graphical_model::get_factor (findex idx) const inline
Accessor for a factor.
Parameters
idx The index of the factor
Returns
the factor corresponding to that index.
Definition at line 437 of file graphical_model.h.
References m_factors.
Referenced by merlin::lbp::accept_incoming(), merlin::factor_graph::adjacent_vars(), merlin::gibbs::init(), merlin::lbp::init(), merlin::bte::init(), merlin::ijgp::init(), merlin::wmb::init(), merlin::factor_graph::is_var_node(), largest(), logP(), markov_blanket(), max_sequential(), max_simple(), remove_factor(), merlin::gibbs::run(), merlin::lbp::run(), smallest(), and merlin::factor_graph::span_tree().
const std::vector<factor>& merlin::graphical_model::get_factors () const inline
Accessor for the factor container.
Returns
the list of factors of the model.
Definition at line 445 of file graphical_model.h.
References m_factors.
Referenced by merlin::bte::init(), merlin::ijgp::init(), merlin::wmb::init(), Merlin::run(), and merlin::jglp::run().
void merlin::graphical_model::improve_order (OrderMethod ord_type, double & old_score, variable_order_t & old_order) const inline
Look for a better order iteratively.
Parameters
ord_type The variable ordering method
old_score The best score found so far
old_order The order corresponding to the best score so far
Definition at line 1278 of file graphical_model.h.
References _vindex(), merlin::variable_set::begin(), merlin::variable_set::end(), merlin::variable_set::erase(), merlin::variable_set::insert(), merlin::variable::label(), mrf(), nvar(), order(), order_score(), and var().
size_t merlin::graphical_model::induced_width (const variable_order_t & order) const inline
Find the induced width (complexity) of an elimination order.
Parameters
order The variable elimination order
Returns
the induced width of the elimination order.
Definition at line 698 of file graphical_model.h.
References _vindex(), merlin::graph::add_edge(), merlin::set< T >::begin(), merlin::variable_set::begin(), merlin::set< T >::end(), merlin::variable_set::end(), mrf(), merlin::graph::neighbors(), and var().
Referenced by merlin::jglp::init(), merlin::bte::init(), merlin::ijgp::init(), and merlin::wmb::init().
void merlin::graphical_model::insert (std::vector< flist > & adj, findex idx, const variable_set & vs) inline
Add the scope of a factor to the adjacency list.
Parameters
adj The adjacency list to be modified
idx The index of the factor
vs The scope of the factor
Definition at line 1347 of file graphical_model.h.
References merlin::variable::label(), merlin::variable_set::nvar(), and merlin::variable_set::rbegin().
Referenced by add_factor(), merlin::bte::init(), merlin::ijgp::init(), merlin::wmb::init(), and merlin::jglp::run().
flist merlin::graphical_model::intersects (const variable_set & vs) const inline
Intersection of factors depending on a set of variables.
Parameters
vs The set of variable object
Returns
the list of factor indexes containing those variables in their scopes.
Definition at line 478 of file graphical_model.h.
References merlin::variable_set::size(), and with_variable().
Referenced by contained_by().
bool merlin::graphical_model::is_binary () const inline
Check if a binary model.
Returns
true if all variables have at most two values in their domains. Otherwise return false.
Definition at line 649 of file graphical_model.h.
bool merlin::graphical_model::is_pairwise () const inline
Check if a pairwise model.
Returns
true if all factors involve at most two variables. Otherwise return false.
Definition at line 662 of file graphical_model.h.
References m_factors, num_factors(), and nvar().
factor merlin::graphical_model::joint (size_t maxsize = 0) const inline
Directly calculate joint distribution function.
Parameters
maxsize The maximum size allowed for the joint distribution
Returns
the factor representing the full joint distribution of the model.
Definition at line 676 of file graphical_model.h.
References m_factors, num_factors(), and nvar().
findex merlin::graphical_model::largest (const flist & fl) inline
Find the factor with the largest scope.
Parameters
fl The reference to a list of factors
Returns
the index of the largest factor (scope-wise).
Definition at line 633 of file graphical_model.h.
References merlin::set< T >::begin(), merlin::set< T >::end(), get_factor(), merlin::factor::nvar(), and merlin::set< T >::size().
variable_set merlin::graphical_model::markov_blanket (const variable & v) const inline
Markov blanket of a variable.
Parameters
v The variable object
Returns
the set of variables that form the Markov blanket (ie, the variables that v may depend on).
Definition at line 522 of file graphical_model.h.
References merlin::set< T >::begin(), merlin::set< T >::end(), get_factor(), merlin::factor::vars(), and with_variable().
Referenced by markov_blanket(), and mrf().
variable_set merlin::graphical_model::markov_blanket (const variable_set & vs) const inline
Markov blanket of a set of variables.
Parameters
vs The set of variables
Returns
the union of Markov blankets corresponding to the variables in the input set.
Definition at line 537 of file graphical_model.h.
References markov_blanket(), and merlin::variable_set::size().
std::vector<variable_set> merlin::graphical_model::mrf () const inline
Full adjacency matrix.
Returns
the adjacency list associated with each variable in the model.
Definition at line 548 of file graphical_model.h.
References markov_blanket(), nvar(), and var().
Referenced by improve_order(), induced_width(), order(), order2(), pseudo_tree(), and pseudo_tree_size().
graphical_model& merlin::graphical_model::operator= (const graphical_model & gm) inline
Assignment operator (deep copy).
Parameters
gm The graphical model to be copied from
Returns
a reference to the modified object containing the copied content.
Definition at line 79 of file graphical_model.h.
References m_factors, and m_markov.
variable_order_t merlin::graphical_model::order (OrderMethod ord_type) const inline
Find a variable elimination order.
Parameters
ord_type The ordering method
Returns
the variable ordering corresponding to the method, such that the first variable in the ordering is eliminated first.
Definition at line 821 of file graphical_model.h.
References _vindex(), merlin::variable_set::begin(), merlin::variable_set::end(), merlin::variable_set::erase(), merlin::variable_set::insert(), merlin::variable::label(), mrf(), nvar(), order_score(), merlin::variable_set::size(), and var().
Referenced by improve_order(), merlin::jglp::init(), merlin::bte::init(), merlin::ijgp::init(), order(), order2(), and order_random().
variable_order_t merlin::graphical_model::order (OrderMethod ord_type, std::vector< bool > var_types) const inline
Find a constrained variable elimination order.
Parameters
ord_type The ordering method
var_types The vector containing the variable types (SUM or MAX)
Returns
the constrained variable ordering corresponding to the method, such that SUM variables are eliminated before any of the MAX variables.
Definition at line 1188 of file graphical_model.h.
References _vindex(), merlin::variable_set::begin(), merlin::variable_set::contains(), merlin::variable_set::end(), merlin::variable_set::erase(), merlin::variable_set::insert(), merlin::variable::label(), mrf(), nvar(), order(), order_score(), merlin::variable_set::size(), and var().
variable_order_t merlin::graphical_model::order2 (OrderMethod ord_type) const inline
Find a variable elimination order.
Parameters
ord_type The ordering method
Returns
the variable ordering corresponding to the method, such that the first variable in the ordering is eliminated first.
Definition at line 878 of file graphical_model.h.
References merlin::graph::add_edge(), merlin::set< T >::begin(), merlin::variable_set::begin(), merlin::set< T >::end(), merlin::variable_set::end(), merlin::variable::label(), mrf(), merlin::graph::neighbors(), merlin::graph::num_nodes(), nvar(), order(), order_score(), merlin::graph::remove_edge(), merlin::graph::remove_node(), merlin::set< T >::size(), and var().
Referenced by merlin::wmb::init().
variable_order_t merlin::graphical_model::order2 (OrderMethod ord_type, std::vector< bool > var_types) const inline
Find a constrained variable elimination order.
Parameters
ord_type The ordering method
var_types The vector containing the variable types (SUM or MAX)
Returns
the constrained variable ordering corresponding to the method, such that SUM variables are eliminated before any of the MAX variables.
Definition at line 1027 of file graphical_model.h.
References _vindex(), merlin::graph::add_edge(), merlin::set< T >::begin(), merlin::variable_set::begin(), merlin::set< T >::end(), merlin::variable_set::end(), mrf(), merlin::graph::neighbors(), merlin::graph::num_nodes(), nvar(), order(), order_score(), merlin::graph::remove_edge(), merlin::graph::remove_node(), and merlin::set< T >::size().
double merlin::graphical_model::order_score (const std::vector< variable_set > & adj, size_t i, OrderMethod kOType) const inline protected
Compute the score of a variable for the elimination order.
Parameters
adj The adjacency lists
i The index of the variable
kOType The variable elimination order
Returns
the score of the variable.
Definition at line 1489 of file graphical_model.h.
References _vindex(), merlin::set< T >::begin(), merlin::graph::edge(), merlin::set< T >::end(), merlin::graph::neighbors(), merlin::edge_id::NO_EDGE, merlin::variable_set::num_states(), merlin::variable::states(), and var().
Referenced by improve_order(), order(), and order2().
std::vector<vindex> merlin::graphical_model::pseudo_tree (const variable_order_t & order) const inline
Find the pseudo tree corresponding to an elimination order.
Parameters
order The reference of a variable elimination order
Returns
the pseudo tree corresponding to the elimination order
Definition at line 786 of file graphical_model.h.
References _vindex(), merlin::variable_set::begin(), merlin::variable_set::contains(), merlin::variable_set::end(), MER_ENUM(), mrf(), nvar(), and var().
Referenced by merlin::jglp::init(), merlin::bte::init(), merlin::ijgp::init(), and merlin::wmb::init().
std::pair<size_t, size_t> merlin::graphical_model::pseudo_tree_size (const variable_order_t & order) const inline
Find induced width and pseudo tree height of an elimination order.
Parameters
order The reference of a variable elimination order
Returns
the pair representing the induced width and height of the pseudo tree corresponding to the variable elimination order.
Definition at line 756 of file graphical_model.h.
References _vindex(), merlin::variable_set::begin(), merlin::variable_set::end(), mrf(), nvar(), and var().
void merlin::graphical_model::read (const char * file_name) inline
Read the graphical model from a file in the UAI format.
For details on the UAI file format see the main documentation of the library. In this format, the factor tables are assumed to be represented using the "least significant bit", namely the last variable in the factor scope changes the fastest. Moreover, the internal representation of the factor assumes that the scope is ordered lexicographically.
Parameters
file_name The full path to the file
Definition at line 136 of file graphical_model.h.
References merlin::convert_index::convert(), fixup(), m_factors, m_markov, MERLIN_EPSILON, and nvar().
Referenced by Merlin::read_model().
virtual void merlin::graphical_model::remove_factor (findex idx) inline virtual
Remove a factor from the model.
Parameters
idx The index of the factor to be removed
Reimplemented in merlin::factor_graph.
Definition at line 598 of file graphical_model.h.
References erase(), get_factor(), m_factors, and merlin::graph::remove_node().
Referenced by merlin::factor_graph::remove_factor().
findex merlin::graphical_model::smallest (const flist & fl) inline
Find the factor with the smallest scope.
Parameters
fl The reference to a list of factors
Returns
the index of the smallest factor (scope-wise).
Definition at line 619 of file graphical_model.h.
References merlin::set< T >::begin(), merlin::set< T >::end(), get_factor(), merlin::factor::nvar(), and merlin::set< T >::size().
Referenced by max_simple().
variable merlin::graphical_model::var (vindex i) const inline
Convert a variable index to Var object.
Parameters
i The variable index to be converted
Returns
the Var object corresponding to the index.
Definition at line 421 of file graphical_model.h.
Referenced by assert_evidence(), merlin::jglp::config(), merlin::factor_graph::create_factor_graph(), merlin::bte::forward(), merlin::wmb::forward(), improve_order(), induced_width(), merlin::gibbs::init(), merlin::bte::init(), merlin::ijgp::init(), merlin::wmb::init(), merlin::wmb::match_clusters(), max_sequential(), max_simple(), mrf(), order(), order2(), order_random(), order_score(), pseudo_tree(), pseudo_tree_size(), merlin::gibbs::run(), merlin::ijgp::run(), merlin::bte::run(), merlin::wmb::run(), merlin::lbp::run(), merlin::jglp::run(), merlin::factor_graph::span_tree(), merlin::bte::update(), merlin::ijgp::update(), merlin::wmb::update(), merlin::bte::write_solution(), merlin::wmb::write_solution(), merlin::ijgp::write_solution(), merlin::lbp::write_solution(), and merlin::gibbs::write_solution().
const flist& merlin::graphical_model::with_variable (const variable & v) const inline
Factors depending on a variable.
Parameters
v The variable object
Returns
the list of factor indexes containing the variable in their scopes.
Definition at line 456 of file graphical_model.h.
References _vindex().
Referenced by merlin::gibbs::belief(), contains(), merlin::bte::init(), merlin::ijgp::init(), merlin::wmb::init(), intersects(), markov_blanket(), max_sequential(), max_simple(), merlin::gibbs::run(), merlin::jglp::run(), and with_variable_set().
flist merlin::graphical_model::with_variable_set (const variable_set & vs) const inline
Union of factors depending on a set of variables.
Parameters
vs The set of variable object
Returns
the list of factor indexes containing those variables in their scopes.
Definition at line 465 of file graphical_model.h.
References merlin::variable_set::size(), and with_variable().
Referenced by contains().
void merlin::graphical_model::write (const char * file_name) inline
Write the graphical model to a file using the UAI format.
For details on the UAI file format see the main documentation of the library. In this format, the factor tables are assumed to be represented using the "least significant bit", namely the last variable in the factor scope changes the fastest. Moreover, the internal representation of the factor assumes that the scope is ordered lexicographically.
Definition at line 214 of file graphical_model.h.
References merlin::variable_set::begin(), merlin::variable_set::end(), m_factors, num_factors(), merlin::factor::numel(), merlin::factor::nvar(), nvar(), and merlin::factor::vars().
Referenced by Merlin::write_model().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const graphical_model & gm) friend
Output operator.
Parameters
out The reference of an output stream
gm The reference of a graphical model
Returns
the reference of the modified output stream containing the formatted content of the graphical model.
Definition at line 1420 of file graphical_model.h.
The documentation for this class was generated from the following file:
src/include/graphical_model.h