Merlin: merlin::variable_set Class Reference
merlin::variable_set Class Reference
#include <variable_set.h>
Classes
class const_iterator
Public Types
typedef size_t vindex
Variable IDs.
typedef size_t vsize
Dimension (cardinality) of variables.
typedef const_iterator const_reverse_iterator
A reverse const iterator.
Public Member Functions
variable_set (void)
Default constructor.
variable_set (const variable_set &vs)
Copy constructor.
variable_set (const variable &v)
Constructor with a single variable.
variable_set (const variable &v, const variable &v2)
Constructor with a pair of variables.
template<typename Iter >
variable_set (Iter B, Iter E, size_t size_hint=0)
Constructor with input iterators.
~variable_set (void)
Destructor.
variable_set & operator= (const variable_set &B)
Assignment operator.
void swap (variable_set &v)
Swap two variable sets.
const size_t size () const
Return the size of the set.
const size_t nvar () const
Return the number of variables.
const vsize * dims () const
Return the dimensions of variables.
size_t num_states () const
Return the cartesian product of the domains.
const variable operator[] (size_t c) const
Index operator.
bool operator== (const variable_set &B) const
Compare sets of variables under lexicographical order (A == B).
bool operator!= (const variable_set &B) const
Compare sets of variables under lexicographical order (A != B).
bool operator< (const variable_set &t) const
Compare sets of variables under lexicographical order (A < B).
bool operator<= (const variable_set &t) const
Compare sets of variables under lexicographical order (A <= B).
bool operator> (const variable_set &t) const
Compare sets of variables under lexicographical order (A > B).
bool operator>= (const variable_set &t) const
Compare sets of variables under lexicographical order (A >= B).
const_iterator begin () const
Return the iterator to the beginning of the set.
const_iterator end () const
Return the iterator to the end of the set.
const_reverse_iterator rbegin () const
Return the reverse iterator to the beginning of the set.
const_reverse_iterator rend () const
Return the reverse iterator to the end of the set.
variable_set & operator+= (const variable_set &B)
Union over sets (+=).
variable_set operator| (const variable_set &B) const
Union over sets (|).
variable_set & operator|= (const variable_set &B)
Union over sets (|=).
variable_set operator/ (const variable_set &B) const
Difference over sets (/).
variable_set & operator/= (const variable_set &B)
Difference over sets (/=).
variable_set & operator&= (const variable_set &B)
Intersection over sets (&=).
variable_set & operator^= (const variable_set &B)
Symmetric Difference over sets (^ xor).
variable_set operator+ (const variable &B) const
Union with a single variable.
variable_set & operator+= (const variable &B)
Union with a single variable.
variable_set operator| (const variable &B) const
Union with a single variable.
variable_set & operator|= (const variable &B)
Union with a single variable.
variable_set operator- (const variable &B) const
Set-difference with a single variable.
variable_set & operator-= (const variable &B)
Set-difference with a single variable.
variable_set operator/ (const variable &B) const
Set-difference with a single variable.
variable_set & operator/= (const variable &B)
Set-difference with a single variable.
variable_set operator& (const variable &B) const
Intersection with a single variable.
variable_set & operator&= (const variable &B)
Intersection with a single variable.
variable_set operator^ (const variable &B) const
Set-symmetric difference with a single variable.
variable_set & operator^= (const variable &B)
Set-symmetric difference with a single variable.
variable_set operator+ (const variable_set &B) const
Union over sets (+).
variable_set operator- (const variable_set &B) const
Difference over sets (-).
variable_set & operator-= (const variable_set &B)
Difference over sets (-).
variable_set operator& (const variable_set &B) const
Intersection over sets (&).
variable_set operator^ (const variable_set &B) const
Symmetric difference over sets (xor).
variable_set & insert (const variable &v)
Add a new variable to the set.
variable_set & erase (const variable &v)
Remove a variable from the set.
bool operator<< (const variable_set &S) const
Check if another set includes the current set this.
bool operator>> (const variable_set &S) const
Check if the current set this includes another set.
bool intersects (const variable_set &S) const
Check if the current set this intersects another set.
bool contains (const variable &v) const
Check if the current set contains a given variable.
Protected Member Functions
bool islocal ()
Check for local storage of dimensions.
variable_set (const size_t nv)
"Reserved memory" constructor.
Protected Attributes
std::vector< vindex > m_v
Variable IDs (sorted)
std::vector< vsize > m_dlocal
Non-const version (equals d_) if we allocated the dimensions ourselves.
const vsize * m_d
Dimensions of the variables.
Friends
std::ostream & operator<< (std::ostream &os, variable_set const &v)
Output operator.
Detailed Description
Define a set of variables (ie, the scope of a factor).
Definition at line 38 of file variable_set.h.
Member Function Documentation
variable_set merlin::variable_set::operator& (const variable_set & B) const inline
Intersection over sets (&).
Parameters
B The input set of variables
Returns
the reference to the modified this object representing the intersection between this and set B received as input.
Definition at line 586 of file variable_set.h.
References m_d, m_dlocal, m_v, and size().
variable_set& merlin::variable_set::operator&= (const variable_set & B) inline
Intersection over sets (&=).
Parameters
B The input set of variables
Returns
the reference to the modified this object representing the intersection between this and set B received as input.
Definition at line 383 of file variable_set.h.
variable_set merlin::variable_set::operator+ (const variable_set & B) const inline
Union over sets (+).
Parameters
B The input set of variables
Returns
the set representing the union between this and set B received as input.
Definition at line 492 of file variable_set.h.
References m_d, m_dlocal, m_v, and size().
variable_set& merlin::variable_set::operator+= (const variable_set & B) inline
Union over sets (+=).
Parameters
B The input set of variables
Returns
the reference to the modified this object representing the union between this and set B received as input.
Definition at line 332 of file variable_set.h.
variable_set merlin::variable_set::operator- (const variable_set & B) const inline
Difference over sets (-).
Parameters
B The input set of variables
Returns
the set representing the set-difference between this and set B received as input.
Definition at line 528 of file variable_set.h.
References m_dlocal, m_v, and size().
variable_set& merlin::variable_set::operator-= (const variable_set & B) inline
Difference over sets (-).
Parameters
B The input set of variables
Returns
the reference to the modified this object representing the set-difference between this and set B received as input.
Definition at line 557 of file variable_set.h.
References m_dlocal, m_v, and size().
variable_set merlin::variable_set::operator/ (const variable_set & B) const inline
Difference over sets (/).
Parameters
B The input set of variables
Returns
the reference to the modified this object representing the set-difference between this and set B received as input.
Definition at line 363 of file variable_set.h.
variable_set& merlin::variable_set::operator/= (const variable_set & B) inline
Difference over sets (/=).
Parameters
B The input set of variables
Returns
the reference to the modified this object representing the set-difference between this and set B received as input.
Definition at line 372 of file variable_set.h.
variable_set merlin::variable_set::operator^ (const variable_set & B) const inline
Symmetric difference over sets (xor).
Parameters
B The input set of variables
Returns
the set representing the set-symmetric difference between this and set B received as input.
Definition at line 612 of file variable_set.h.
References m_d, m_dlocal, m_v, and size().
variable_set& merlin::variable_set::operator^= (const variable_set & B) inline
Symmetric Difference over sets (^ xor).
Parameters
B The input set of variables
Returns
the reference to the modified this object representing the set-symmetric difference (xor) between this and set B received as input.
Definition at line 395 of file variable_set.h.
variable_set merlin::variable_set::operator| (const variable_set & B) const inline
Union over sets (|).
Parameters
B The input set of variables
Returns
the reference to the modified this object representing the union between this and set B received as input.
Definition at line 342 of file variable_set.h.
variable_set& merlin::variable_set::operator|= (const variable_set & B) inline
Union over sets (|=).
Parameters
B The input set of variables
Returns
the reference to the modified this object representing the union between this and set B received as input.
Definition at line 352 of file variable_set.h.
The documentation for this class was generated from the following file:
src/include/variable_set.h