Merlin: merlin::gibbs Class Reference
merlin::gibbs Class Reference
Factor graph algorithm specialization for Gibbs sampling.
#include <gibbs.h>
Public Types
typedef graphical_model::findex findex
Factor index.
typedef graphical_model::vindex vindex
Variable index.
typedef graphical_model::flist flist
Collection of factor indices.
Public Types inherited from merlin::graphical_model
typedef size_t findex
Factor index.
typedef size_t vindex
Variable index.
typedef set< findex > flist
Collection of factor indices.
Public Types inherited from merlin::graph
typedef edge_id::index index
Basic indexing type for the graph.
Public Member Functions
gibbs ()
Creates an empty Gibbs sampler.
gibbs (const graphical_model &fg)
Creates a Gibbs sampler from an existing graphical model.
gibbs * clone () const
Clone the Gibbs sampler.
MER_ENUM (Property, Task, TempMin, TempMax, Iter, Samples, Debug)
Properties of the sampler.
virtual void set_properties (std::string opt=std::string())
Set the properties of the sampler.
void init ()
Initialize the Gibbs sampler.
void run ()
Run the Gibbs sampler.
double lb () const
Lower bound on the optimal value.
double ub () const
Upper bound on the optimal value.
std::vector< index > best_config () const
Best configuration.
double logZ () const
Log value of the partition function.
double logZub () const
Upper bound on the log partition function.
double logZlb () const
Lower bound on the log partition function.
const std::vector< std::vector< index > > & samples ()
Return the list of samples.
const factor & belief (size_t i) const
Belief associated with a node of the graph.
const factor & belief (variable v) const
Belief associated with a particular variable.
const factor & belief (variable_set vs) const
Belief associated with a set of variables.
const std::vector< factor > & beliefs () const
Beliefs associated with the variables.
void write_solution (const char *file_name, const std::map< size_t, size_t > &evidence, const std::map< size_t, size_t > &old2new, const graphical_model &orig)
Write the solution to the output file.
MER_ENUM (Task, PR, MAR, MAP)
Inference tasks supported.
Public Member Functions inherited from merlin::graphical_model
graphical_model ()
Creates an empty graphical model.
graphical_model (const graphical_model &gm)
Creates a graphical model by copying an existing one.
graphical_model & operator= (const graphical_model &gm)
Assignment operator (deep copy).
virtual graphical_model * clone ()
Clone the graphical model.
graphical_model (std::vector< factor > fs)
Constructor from a list of factors.
template<class InputIterator >
graphical_model (InputIterator first, InputIterator last)
Creates a graphical model from input iterators.
virtual ~graphical_model ()
Destroys the graphical model.
void read (const char *file_name)
Read the graphical model from a file in the UAI format.
void write (const char *file_name)
Write the graphical model to a file using the UAI format.
bool is_markov ()
Check if graphical model is a Markov or a Bayes net.
std::vector< factor > assert_evidence (const char *file_name, std::map< size_t, size_t > &evidence, std::map< size_t, size_t > &old_to_new)
Assert evidence into the graphical model.
std::vector< factor > assert_evidence (const std::map< size_t, size_t > &evidence, std::map< size_t, size_t > &old_to_new)
Assert evidence into the graphical model.
size_t nvar () const
Return the number of variables in the model.
variable var (vindex i) const
Convert a variable index to Var object.
size_t num_factors () const
Return the number of factors in the model.
const factor & get_factor (findex idx) const
Accessor for a factor.
const std::vector< factor > & get_factors () const
Accessor for the factor container.
const flist & with_variable (const variable &v) const
Factors depending on a variable.
flist with_variable_set (const variable_set &vs) const
Union of factors depending on a set of variables.
flist intersects (const variable_set &vs) const
Intersection of factors depending on a set of variables.
flist contains (const variable &v) const
Factors depending on a variable.
flist contains (const variable_set &vs) const
Union of factors depending on a set of variables.
flist contained_by (const variable_set &vs) const
Factors contained by a set of variables.
variable_set markov_blanket (const variable &v) const
Markov blanket of a variable.
variable_set markov_blanket (const variable_set &vs) const
Markov blanket of a set of variables.
std::vector< variable_set > mrf () const
Full adjacency matrix.
virtual findex add_factor (const factor &F)
Add a new factor to the model.
virtual void remove_factor (findex idx)
Remove a factor from the model.
void clear_factors ()
Remove all factors.
findex smallest (const flist &fl)
Find the factor with the smallest scope.
findex largest (const flist &fl)
Find the factor with the largest scope.
bool is_binary () const
Check if a binary model.
bool is_pairwise () const
Check if a pairwise model.
factor joint (size_t maxsize=0) const
Directly calculate joint distribution function.
size_t induced_width (const variable_order_t &order) const
Find the induced width (complexity) of an elimination order.
std::pair< size_t, size_t > pseudo_tree_size (const variable_order_t &order) const
Find induced width and pseudo tree height of an elimination order.
std::vector< vindex > pseudo_tree (const variable_order_t &order) const
Find the pseudo tree corresponding to an elimination order.
MER_ENUM (OrderMethod, MinFill, WtMinFill, MinWidth, WtMinWidth, Random)
Variable ordering methods.
variable_order_t order (OrderMethod ord_type) const
Find a variable elimination order.
variable_order_t order2 (OrderMethod ord_type) const
Find a variable elimination order.
variable_order_t order2 (OrderMethod ord_type, std::vector< bool > var_types) const
Find a constrained variable elimination order.
variable_order_t order (OrderMethod ord_type, std::vector< bool > var_types) const
Find a constrained variable elimination order.
void improve_order (OrderMethod ord_type, double &old_score, variable_order_t &old_order) const
Look for a better order iteratively.
void insert (std::vector< flist > &adj, findex idx, const variable_set &vs)
Add the scope of a factor to the adjacency list.
void erase (std::vector< flist > &adj, findex idx, const variable_set &vs)
Remove the scope of a factor from the adjacency list.
std::vector< size_t > max_simple ()
Find smallest factor with each variable and select its optimum.
std::vector< size_t > max_sequential (const variable_order_t &order)
Find maxmarginal for variable and select optimum given those so far.
double logP (const std::vector< size_t > &config)
Compute the log-probability of a particular (complete) configuration.
double get_global_const () const
Return the constant resulted from asserting evidence in the model.
Public Member Functions inherited from merlin::graph
graph (size_t n=0)
Constructs a graph with n vertices and 0 edges.
~graph ()
Destroys the graph.
index add_node ()
Add a node to the graph.
void remove_node (index i)
Remove a node from the graph.
size_t num_nodes ()
Return the number of nodes.
size_t num_edges ()
Return the number of edges.
const edge_id & add_edge (index i, index j)
Add an edge to the graph.
void remove_edge (index i, index j)
Remove an edge from the graph.
void clear ()
Clear the graph by removing all nodes and edges.
void clear_edges ()
Remove all edges.
const edge_id & edge (index i, index j) const
Return the edge (if any) between two nodes.
const set< edge_id > & neighbors (index i) const
Return the neighbors of a node (ie, adjacency list).
const edge_id & edge (index eij) const
Return an edge (by its index).
const std::vector< edge_id > & edges () const
Return the edges of the graph.
Public Member Functions inherited from merlin::algorithm
algorithm ()
Constructs an empty algorithm.
virtual ~algorithm ()
Destructs the algorithm.
void set_stop_iter (double d)
Set the number of iterations.
void set_stop_obj (double d)
Set the minumum objective change before stopping.
void set_stop_msg (double d)
Set the minimum ammount a message changes before stopping.
Additional Inherited Members
Public Attributes inherited from merlin::graph
std::vector< set< edge_id > > m_adj
Look up EdgeID info by adj[i][jj] (jj = position of j).
std::vector< edge_id > m_edges
Look up EdgeID info by edges[eij] (edge index).
Protected Member Functions inherited from merlin::graphical_model
size_t _vindex (const variable &v) const
Look up the index of a variable.
flist & _with_variable (const variable &v)
Mutable accessor of adjacency.
void fixup ()
Internal function for ensuring consistency of the model.
double order_score (const std::vector< variable_set > &adj, size_t i, OrderMethod kOType) const
Compute the score of a variable for the elimination order.
variable_order_t order_random () const
Create a random elimination order.
Protected Attributes inherited from merlin::graphical_model
std::vector< factor > m_factors
Collection of all factors in the model.
bool m_markov
Markov or Bayes network. Default is true (Markov)
Protected Attributes inherited from merlin::graph
std::stack< index > m_vvacant
List of available vertex ids.
std::stack< index > m_evacant
List of available edge ids.
Protected Attributes inherited from merlin::algorithm
double m_stop_iter
Stopping criteria (iterations)
double m_stop_obj
Stopping criteria (objective change)
double m_stop_msg
Stopping criteria (message change)
double m_start_time
Start time.
Detailed Description
Factor graph algorithm specialization for Gibbs sampling.
Definition at line 37 of file gibbs.h.
Member Function Documentation
const factor& merlin::gibbs::belief (size_t i) const inline virtual
Belief associated with a node of the graph.
Returns
the belief associated with a node of the graph. Nodes correspond typically to variables. The belied is a function represented by the Factor class.
Parameters
i The index of the node in the graph (from 0)
Implements merlin::algorithm.
Definition at line 304 of file gibbs.h.
Referenced by belief(), run(), and write_solution().
const factor& merlin::gibbs::belief (variable v) const inline virtual
Belief associated with a particular variable.
Parameters
v The variable to compute the belief of
Returns
the belief associated with a particular variable in the graphical model. The belief is a function represented by the Factor class.
Implements merlin::algorithm.
Definition at line 307 of file gibbs.h.
References belief(), and merlin::graphical_model::with_variable().
const factor& merlin::gibbs::belief (variable_set vs) const inline virtual
Belief associated with a set of variables.
Parameters
vs The set of variables to compute the belief of
Returns
the belief associated with a set of variables in the graphical model. The belief is a function represented by the Factor class.
Implements merlin::algorithm.
Definition at line 310 of file gibbs.h.
const std::vector<factor>& merlin::gibbs::beliefs () const inline virtual
Beliefs associated with the variables.
Returns
the beliefs associated with the variables in the graphical model (one belief for each of the variables). The output vector is indexed by the same indexes used for the variables.
Implements merlin::algorithm.
Definition at line 313 of file gibbs.h.
std::vector<index> merlin::gibbs::best_config () const inline virtual
Best configuration.
Returns
a vector containing the best configuration of the variables (i.e., variable value assignments) found so far. It is specific to optimization tasks (e.g., MAP, Marginal MAP).
Implements merlin::algorithm.
Definition at line 284 of file gibbs.h.
gibbs* merlin::gibbs::clone () const inline virtual
Clone the Gibbs sampler.
Returns
the pointer to the cloned sampler.
Implements merlin::algorithm.
Definition at line 65 of file gibbs.h.
References gibbs(), and MER_ENUM().
double merlin::gibbs::lb () const inline virtual
Lower bound on the optimal value.
Returns
a lower bound on the optimal value defined by the inference task if available.
Implements merlin::algorithm.
Definition at line 278 of file gibbs.h.
double merlin::gibbs::logZ () const inline virtual
Log value of the partition function.
Returns
an estimate the log parition function. If the inference algorithm is an exact one then the return value is the exact log value of the partition function.
Implements merlin::algorithm.
Definition at line 287 of file gibbs.h.
double merlin::gibbs::logZlb () const inline virtual
Lower bound on the log partition function.
Returns
a lower bound on the log value of the parition function.
Implements merlin::algorithm.
Definition at line 293 of file gibbs.h.
double merlin::gibbs::logZub () const inline virtual
Upper bound on the log partition function.
Returns
an upper bound on the log value of the parition function. Most inference algorithms implemented in merlin support upper bounds on the log partition function.
Implements merlin::algorithm.
Definition at line 290 of file gibbs.h.
virtual void merlin::gibbs::set_properties (std::string opt = std::string()) inline virtual
Set the properties of the sampler.
Parameters
opt The string of comma separated property value pairs
Definition at line 79 of file gibbs.h.
References merlin::graphical_model::nvar().
Referenced by gibbs(), and Merlin::run().
double merlin::gibbs::ub () const inline virtual
Upper bound on the optimal value.
Returns
an upper bound on the optimal value defined by the inference task. It is specific to optimization tasks such as MAP and Marginal MAP inference.
Implements merlin::algorithm.
Definition at line 281 of file gibbs.h.
void merlin::gibbs::write_solution (const char * file_name, const std::map< size_t, size_t > & evidence, const std::map< size_t, size_t > & old2new, const graphical_model & orig) inline
Write the solution to the output file.
Parameters
filename The output file name
evidence The evidence variable value pairs
old2new The mapping between old and new variable indexing
orig The graphical model prior to asserting evidence
Definition at line 325 of file gibbs.h.
References belief(), MER_ENUM(), merlin::graphical_model::nvar(), merlin::variable::states(), and merlin::graphical_model::var().
Referenced by Merlin::run().
The documentation for this class was generated from the following file:
src/include/gibbs.h