Merlin: merlin::jglp Class Reference
merlin::jglp Class Reference
#include <jglp.h>
Classes
struct sPair
Helper class for pairs of sorted indices.
Public Types
typedef graphical_model::findex findex
Factor index.
typedef graphical_model::vindex vindex
Variable index.
typedef graphical_model::flist flist
Collection of factor indices.
typedef flist::const_iterator flistIt
Iterator for collection of factor indeces.
Public Types inherited from merlin::graphical_model
typedef size_t findex
Factor index.
typedef size_t vindex
Variable index.
typedef set< findex > flist
Collection of factor indices.
Public Types inherited from merlin::graph
typedef edge_id::index index
Basic indexing type for the graph.
Public Member Functions
jglp ()
Default constructor.
jglp (const graphical_model &gm)
Constructor.
virtual jglp * clone () const
Clone the algorithm.
double ub () const
Upper bound on the optimal value.
double lb () const
Lower bound on the optimal value.
std::vector< index > best_config () const
Best configuration.
double logZ () const
Log value of the partition function.
double logZub () const
Upper bound on the log partition function.
double logZlb () const
Lower bound on the log partition function.
const factor & belief (size_t f) const
Belief associated with a node of the graph.
const factor & belief (variable v) const
Belief associated with a particular variable.
const factor & belief (variable_set vs) const
Belief associated with a set of variables.
const std::vector< factor > & beliefs () const
Beliefs associated with the variables.
const graphical_model & get_gm_orig () const
Return the original graphical model.
MER_ENUM (Property, iBound, Order, Iter, Debug)
Properties of the algorithm.
void set_ibound (size_t i)
Set the i-bound parameter.
size_t get_ibound () const
Return the i-bound parameter.
void set_order (const variable_order_t &ord)
Set the variable elimination order.
void set_order_method (OrderMethod method)
Set the variable elimination order method.
const variable_order_t & get_order ()
Return the variable elimination order.
const std::vector< vindex > & get_pseudo_tree ()
Return the pseudo tree.
void set_pseudo_tree (const std::vector< vindex > &p)
Set the pseudo tree.
void set_graphical_model (const graphical_model &gm)
Set the graphical model content.
void set_graphical_model (const std::vector< factor > &fs)
Set the graphical model content from a list of factors.
virtual void set_properties (std::string opt=std::string())
Set the properties of the algorithm.
factor elim (const factor &F, const variable_set &vs)
Eliminate a set of variables from a factor.
factor marg (const factor &F, const variable_set &vs)
Compute the marginal over a set of variables.
double score (const std::vector< factor > &fin, const variable &VX, size_t i, size_t j)
Scoring function for bucket aggregation.
void init ()
Initialize the JGLP algorithm.
void tighten (size_t nIter, double stopTime=-1, double stopObj=-1)
Join graph propagation for tightening the bound.
void write_solution (const char *file_name, const std::map< size_t, size_t > &evidence, const std::map< size_t, size_t > &old2new, const graphical_model &orig)
Write the solution to the output file.
void run ()
Run the algorithm.
std::vector< index > config ()
Return the MAP configuration following the propagation.
Public Member Functions inherited from merlin::graphical_model
graphical_model ()
Creates an empty graphical model.
graphical_model (const graphical_model &gm)
Creates a graphical model by copying an existing one.
graphical_model & operator= (const graphical_model &gm)
Assignment operator (deep copy).
virtual graphical_model * clone ()
Clone the graphical model.
graphical_model (std::vector< factor > fs)
Constructor from a list of factors.
template<class InputIterator >
graphical_model (InputIterator first, InputIterator last)
Creates a graphical model from input iterators.
virtual ~graphical_model ()
Destroys the graphical model.
void read (const char *file_name)
Read the graphical model from a file in the UAI format.
void write (const char *file_name)
Write the graphical model to a file using the UAI format.
bool is_markov ()
Check if graphical model is a Markov or a Bayes net.
std::vector< factor > assert_evidence (const char *file_name, std::map< size_t, size_t > &evidence, std::map< size_t, size_t > &old_to_new)
Assert evidence into the graphical model.
std::vector< factor > assert_evidence (const std::map< size_t, size_t > &evidence, std::map< size_t, size_t > &old_to_new)
Assert evidence into the graphical model.
size_t nvar () const
Return the number of variables in the model.
variable var (vindex i) const
Convert a variable index to Var object.
size_t num_factors () const
Return the number of factors in the model.
const factor & get_factor (findex idx) const
Accessor for a factor.
const std::vector< factor > & get_factors () const
Accessor for the factor container.
const flist & with_variable (const variable &v) const
Factors depending on a variable.
flist with_variable_set (const variable_set &vs) const
Union of factors depending on a set of variables.
flist intersects (const variable_set &vs) const
Intersection of factors depending on a set of variables.
flist contains (const variable &v) const
Factors depending on a variable.
flist contains (const variable_set &vs) const
Union of factors depending on a set of variables.
flist contained_by (const variable_set &vs) const
Factors contained by a set of variables.
variable_set markov_blanket (const variable &v) const
Markov blanket of a variable.
variable_set markov_blanket (const variable_set &vs) const
Markov blanket of a set of variables.
std::vector< variable_set > mrf () const
Full adjacency matrix.
virtual findex add_factor (const factor &F)
Add a new factor to the model.
virtual void remove_factor (findex idx)
Remove a factor from the model.
void clear_factors ()
Remove all factors.
findex smallest (const flist &fl)
Find the factor with the smallest scope.
findex largest (const flist &fl)
Find the factor with the largest scope.
bool is_binary () const
Check if a binary model.
bool is_pairwise () const
Check if a pairwise model.
factor joint (size_t maxsize=0) const
Directly calculate joint distribution function.
size_t induced_width (const variable_order_t &order) const
Find the induced width (complexity) of an elimination order.
std::pair< size_t, size_t > pseudo_tree_size (const variable_order_t &order) const
Find induced width and pseudo tree height of an elimination order.
std::vector< vindex > pseudo_tree (const variable_order_t &order) const
Find the pseudo tree corresponding to an elimination order.
MER_ENUM (OrderMethod, MinFill, WtMinFill, MinWidth, WtMinWidth, Random)
Variable ordering methods.
variable_order_t order (OrderMethod ord_type) const
Find a variable elimination order.
variable_order_t order2 (OrderMethod ord_type) const
Find a variable elimination order.
variable_order_t order2 (OrderMethod ord_type, std::vector< bool > var_types) const
Find a constrained variable elimination order.
variable_order_t order (OrderMethod ord_type, std::vector< bool > var_types) const
Find a constrained variable elimination order.
void improve_order (OrderMethod ord_type, double &old_score, variable_order_t &old_order) const
Look for a better order iteratively.
void insert (std::vector< flist > &adj, findex idx, const variable_set &vs)
Add the scope of a factor to the adjacency list.
void erase (std::vector< flist > &adj, findex idx, const variable_set &vs)
Remove the scope of a factor from the adjacency list.
std::vector< size_t > max_simple ()
Find smallest factor with each variable and select its optimum.
std::vector< size_t > max_sequential (const variable_order_t &order)
Find maxmarginal for variable and select optimum given those so far.
double logP (const std::vector< size_t > &config)
Compute the log-probability of a particular (complete) configuration.
double get_global_const () const
Return the constant resulted from asserting evidence in the model.
Public Member Functions inherited from merlin::graph
graph (size_t n=0)
Constructs a graph with n vertices and 0 edges.
~graph ()
Destroys the graph.
index add_node ()
Add a node to the graph.
void remove_node (index i)
Remove a node from the graph.
size_t num_nodes ()
Return the number of nodes.
size_t num_edges ()
Return the number of edges.
const edge_id & add_edge (index i, index j)
Add an edge to the graph.
void remove_edge (index i, index j)
Remove an edge from the graph.
void clear ()
Clear the graph by removing all nodes and edges.
void clear_edges ()
Remove all edges.
const edge_id & edge (index i, index j) const
Return the edge (if any) between two nodes.
const set< edge_id > & neighbors (index i) const
Return the neighbors of a node (ie, adjacency list).
const edge_id & edge (index eij) const
Return an edge (by its index).
const std::vector< edge_id > & edges () const
Return the edges of the graph.
Public Member Functions inherited from merlin::algorithm
algorithm ()
Constructs an empty algorithm.
virtual ~algorithm ()
Destructs the algorithm.
void set_stop_iter (double d)
Set the number of iterations.
void set_stop_obj (double d)
Set the minumum objective change before stopping.
void set_stop_msg (double d)
Set the minimum ammount a message changes before stopping.
Protected Attributes
graphical_model m_gmo
Original graphical model.
OrderMethod m_order_method
Variable ordering heuristic.
size_t m_ibound
Mini-bucket i-bound.
double m_log_z
Log partition function.
double m_lb
Lower bound.
variable_order_t m_order
Elimination ordering.
std::vector< vindex > m_parents
Pseudo tree.
std::vector< index > m_best_config
MAP assignment.
size_t m_num_iter
Number of iterations.
std::vector< flist > m_mini_buckets
Mini-buucket partitionings.
bool m_debug
Internal debugging flag.
Protected Attributes inherited from merlin::graphical_model
std::vector< factor > m_factors
Collection of all factors in the model.
bool m_markov
Markov or Bayes network. Default is true (Markov)
Protected Attributes inherited from merlin::graph
std::stack< index > m_vvacant
List of available vertex ids.
std::stack< index > m_evacant
List of available edge ids.
Protected Attributes inherited from merlin::algorithm
double m_stop_iter
Stopping criteria (iterations)
double m_stop_obj
Stopping criteria (objective change)
double m_stop_msg
Stopping criteria (message change)
double m_start_time
Start time.
Additional Inherited Members
Public Attributes inherited from merlin::graph
std::vector< set< edge_id > > m_adj
Look up EdgeID info by adj[i][jj] (jj = position of j).
std::vector< edge_id > m_edges
Look up EdgeID info by edges[eij] (edge index).
Protected Member Functions inherited from merlin::graphical_model
size_t _vindex (const variable &v) const
Look up the index of a variable.
flist & _with_variable (const variable &v)
Mutable accessor of adjacency.
void fixup ()
Internal function for ensuring consistency of the model.
double order_score (const std::vector< variable_set > &adj, size_t i, OrderMethod kOType) const
Compute the score of a variable for the elimination order.
variable_order_t order_random () const
Create a random elimination order.
Detailed Description
Join-Graph Linear Programming (ie, Weighted mini-buckets for MAP inference)
Tasks supported: MAP
JGLP is a specialization of the weighted mini-bucket algorithm to the MAP inference task. It builds a join graph by running the mini-bucket algorithm schemetically, and then it connects the mini-buckets residing in the same bucket. JGLP shifts costs along the edges of the join graph by matching the max marginals of any two clusters connected by an edge. In practice, the algorithm typically tightens the MAP upper bound, however this is not a guarantee. It keeps track of the tightest upper bound found and its corresponding assignment.
Definition at line 50 of file jglp.h.
Member Function Documentation
const factor& merlin::jglp::belief (size_t i) const inline virtual
Belief associated with a node of the graph.
Returns
the belief associated with a node of the graph. Nodes correspond typically to variables. The belied is a function represented by the Factor class.
Parameters
i The index of the node in the graph (from 0)
Implements merlin::algorithm.
Definition at line 105 of file jglp.h.
const factor& merlin::jglp::belief (variable v) const inline virtual
Belief associated with a particular variable.
Parameters
v The variable to compute the belief of
Returns
the belief associated with a particular variable in the graphical model. The belief is a function represented by the Factor class.
Implements merlin::algorithm.
Definition at line 109 of file jglp.h.
const factor& merlin::jglp::belief (variable_set vs) const inline virtual
Belief associated with a set of variables.
Parameters
vs The set of variables to compute the belief of
Returns
the belief associated with a set of variables in the graphical model. The belief is a function represented by the Factor class.
Implements merlin::algorithm.
Definition at line 113 of file jglp.h.
const std::vector<factor>& merlin::jglp::beliefs () const inline virtual
Beliefs associated with the variables.
Returns
the beliefs associated with the variables in the graphical model (one belief for each of the variables). The output vector is indexed by the same indexes used for the variables.
Implements merlin::algorithm.
Definition at line 117 of file jglp.h.
std::vector<index> merlin::jglp::best_config () const inline virtual
Best configuration.
Returns
a vector containing the best configuration of the variables (i.e., variable value assignments) found so far. It is specific to optimization tasks (e.g., MAP, Marginal MAP).
Implements merlin::algorithm.
Definition at line 91 of file jglp.h.
References m_best_config.
virtual jglp* merlin::jglp::clone () const inline virtual
Clone the algorithm.
Returns
the pointer to the object containing the cloned algorithm.
Implements merlin::algorithm.
Definition at line 80 of file jglp.h.
References jglp().
factor merlin::jglp::elim (const factor & F, const variable_set & vs) inline
Eliminate a set of variables from a factor.
Parameters
F The reference of the factor to eliminate from
vs The set of variables to be eliminated
Returns
the factor resulted from eliminating the set of variables.
Definition at line 262 of file jglp.h.
References merlin::factor::max().
Referenced by run().
double merlin::jglp::lb () const inline virtual
Lower bound on the optimal value.
Returns
a lower bound on the optimal value defined by the inference task if available.
Implements merlin::algorithm.
Definition at line 88 of file jglp.h.
References m_lb.
double merlin::jglp::logZ () const inline virtual
Log value of the partition function.
Returns
an estimate the log parition function. If the inference algorithm is an exact one then the return value is the exact log value of the partition function.
Implements merlin::algorithm.
Definition at line 95 of file jglp.h.
References m_log_z.
double merlin::jglp::logZlb () const inline virtual
Lower bound on the log partition function.
Returns
a lower bound on the log value of the parition function.
Implements merlin::algorithm.
Definition at line 101 of file jglp.h.
References m_log_z.
double merlin::jglp::logZub () const inline virtual
Upper bound on the log partition function.
Returns
an upper bound on the log value of the parition function. Most inference algorithms implemented in merlin support upper bounds on the log partition function.
Implements merlin::algorithm.
Definition at line 98 of file jglp.h.
References m_log_z.
factor merlin::jglp::marg (const factor & F, const variable_set & vs) inline
Compute the marginal over a set of variables.
Parameters
F The reference of the factor to marginalize over
vs The set of variables representing the scope of the marginal
Returns
the factor representing the marginal over the set of variables.
Definition at line 272 of file jglp.h.
References merlin::factor::maxmarginal().
Referenced by run().
void merlin::jglp::run () inline virtual
Run the algorithm.
Solves a probabilistic inference task.
end for: variable elim order
Implements merlin::algorithm.
Definition at line 470 of file jglp.h.
References merlin::graph::add_edge(), merlin::graphical_model::add_factor(), merlin::set< T >::begin(), elim(), merlin::set< T >::end(), merlin::factor::exp(), merlin::graphical_model::get_factors(), init(), merlin::graphical_model::insert(), merlin::factor::log(), merlin::graphical_model::logP(), merlin::graphical_model::m_factors, marg(), merlin::factor::max(), MERLIN_DOUBLE_PRECISION, merlin::graphical_model::num_factors(), merlin::factor::nvar(), merlin::graphical_model::nvar(), merlin::set< T >::size(), tighten(), merlin::graphical_model::var(), and merlin::graphical_model::with_variable().
Referenced by Merlin::run().
double merlin::jglp::score (const std::vector< factor > & fin, const variable & VX, size_t i, size_t j) inline
Scoring function for bucket aggregation.
Parameters
fin The set of factor scopes containing the pair (i,j) to be aggregated
VX The bucket variable
i The index of first scope
j The index of the second pair
Returns
the score that corresponds to aggregating the two scopes. It returns -3 if unable to combine, -1 for scope only aggregation, and otherwise a positive double score.
Definition at line 287 of file jglp.h.
References merlin::factor::nvar(), and merlin::factor::vars().
Referenced by config().
void merlin::jglp::set_graphical_model (const graphical_model & gm) inline
Set the graphical model content.
Parameters
gm The reference to the graphical model object
Definition at line 210 of file jglp.h.
void merlin::jglp::set_graphical_model (const std::vector< factor > & fs) inline
Set the graphical model content from a list of factors.
Parameters
fs The list of factors
Definition at line 218 of file jglp.h.
References merlin::graphical_model::graphical_model().
void merlin::jglp::set_ibound (size_t i) inline
Set the i-bound parameter.
Parameters
i The value of the i-bound (> 1)
Definition at line 156 of file jglp.h.
Referenced by set_properties().
void merlin::jglp::set_order (const variable_order_t & ord) inline
Set the variable elimination order.
Parameters
ord The variable order
Definition at line 171 of file jglp.h.
void merlin::jglp::set_order_method (OrderMethod method) inline
Set the variable elimination order method.
Parameters
method The elimination order method
Definition at line 179 of file jglp.h.
virtual void merlin::jglp::set_properties (std::string opt = std::string()) inline virtual
Set the properties of the algorithm.
Parameters
opt The string containing comma separated property value pairs
Definition at line 226 of file jglp.h.
References set_ibound().
Referenced by jglp(), and Merlin::run().
void merlin::jglp::set_pseudo_tree (const std::vector< vindex > & p) inline
Set the pseudo tree.
Parameters
p The vector representing the pseudo tree
Definition at line 202 of file jglp.h.
void merlin::jglp::tighten (size_t nIter, double stopTime = -1, double stopObj = -1) inline
Join graph propagation for tightening the bound.
Parameters
nIter The number of iterations
stopTime The time limit
stopObj The difference between two successive objective values
Definition at line 366 of file jglp.h.
References config(), merlin::graph::edges(), merlin::graphical_model::m_factors, m_log_z, merlin::algorithm::m_start_time, and merlin::graphical_model::num_factors().
Referenced by run().
double merlin::jglp::ub () const inline virtual
Upper bound on the optimal value.
Returns
an upper bound on the optimal value defined by the inference task. It is specific to optimization tasks such as MAP and Marginal MAP inference.
Implements merlin::algorithm.
Definition at line 85 of file jglp.h.
References m_log_z.
void merlin::jglp::write_solution (const char * file_name, const std::map< size_t, size_t > & evidence, const std::map< size_t, size_t > & old2new, const graphical_model & orig) inline
Write the solution to the output file.
Parameters
filename The output file name
evidence The evidence variable value pairs
old2new The mapping between old and new variable indexing
orig The graphical model prior to asserting evidence
Definition at line 447 of file jglp.h.
References merlin::graphical_model::nvar().
Referenced by Merlin::run().
The documentation for this class was generated from the following file:
src/include/jglp.h