Merlin: merlin::indexed_heap Class Reference
merlin::indexed_heap Class Reference
#include <indexed_heap.h>
Public Member Functions
indexed_heap ()
Default constructor.
template<class InputPIterator , class InputIIterator >
indexed_heap (InputPIterator p_begin, InputPIterator p_end, InputIIterator i_begin)
Constructor.
void clear ()
Clear the heap.
void insert (double p, size_t r)
Insert an element into the heap.
void erase (size_t r)
Remove an id from the heap.
void debug ()
Internal debugging method.
void pop ()
Remove the top element from the heap.
std::pair< double, size_t > top ()
Return the top element from the heap (highest priority).
size_t size ()
Return the size of the heap.
bool empty ()
Check if the heap is empty.
Detailed Description
Indexed Heap : a "reversible" heap from key (double) to unique values (uint, 0..N-1; some can be missing) for which the value can also be used to look up (access) or remove an entry
Mainly this data structure is used in factor- or edge- priority scheduling; the factor or edge index is used as the unique value and its priority is the key. This gives a lightweight priority queue that still enables edges to be easily "reprioritized".
Definition at line 45 of file indexed_heap.h.
Member Function Documentation
void merlin::indexed_heap::erase (size_t r) inline
Remove an id from the heap.
Parameters
r The id to be removed
Definition at line 129 of file indexed_heap.h.
References size().
Referenced by merlin::lbp::accept_incoming(), and pop().
void merlin::indexed_heap::insert (double p, size_t r) inline
Insert an element into the heap.
Parameters
p The value of the key
r The id associated with the key
Definition at line 101 of file indexed_heap.h.
References size().
Referenced by merlin::lbp::init(), and merlin::lbp::update_outgoing().
The documentation for this class was generated from the following file:
src/include/indexed_heap.h