Merlin: merlin::factor Class Reference
merlin::factor Class Reference
Factor for graphical models.
#include <factor.h>
Classes
struct binOpDivide
Functor for binary operation / (division) on the factor table.
struct binOpMinus
Functor for binary operation - (substraction) on the factor table.
struct binOpPlus
Functor for binary operation + (summation) on the factor table.
struct binOpPower
Functor for binary operation ^ (power) on the factor table.
struct binOpTimes
Functor for binary operation * (multiplication) on the factor table.
struct unOpAbs
Functor for absolute value transformation.
struct unOpExp
Functor for exponential value transformation.
struct unOpLog
Functor for natural log value transformation.
struct unOpLog10
Functor for log base 10 value transformation.
struct unOpLogL
Functor for log value transformation.
Public Types
typedef double value
A real value.
typedef variable_set::vindex vindex
Variable identifiers (0...N-1)
typedef variable_set::vsize vsize
Variable values (0...K-1)
Public Member Functions
factor (factor const &f)
Copy-constructor.
factor (const value s=1.0)
Scalar constructor.
factor (variable_set const &vs, value s=1.0)
Constructor.
factor (variable_set const &vs, value *t)
Constructor.
virtual ~factor ()
Class destructor.
factor & operator= (factor const &rhs)
Assignment operator.
void swap (factor &f)
Swap the object contents.
virtual factor * clone ()
Clone from pointer.
void set_dims ()
Set the domain sizes of the scope's variables.
const size_t nvar () const
Size of the factor's scope.
const variable_set & vars () const
Scope of the factor.
const variable_set & variables () const
Scope of the factor.
const vsize * dims () const
Variable dimensions.
const value * table () const
Table of factor values.
size_t num_states () const
Size of the factor's table.
size_t numel () const
Size of the factor's table.
bool isempty () const
Empty factor.
bool isnan () const
Valid factor.
bool isfinite () const
Finite factor.
bool isscalar () const
Scalar (constant) factor.
value operator[] (vsize v) const
Access table elements (const)
value & operator[] (vsize v)
Rewrite table elements (non-const)
value get (vsize i) const
Access table elements (safe)
void set (vsize i, value v)
Rewrite table elements (safe)
factor & fill (value v)
Fill with constant (in-place).
factor & randomize ()
Fill with random values in [0,1).
factor & fill_uniform ()
Fill with 1/N values.
factor & abs (void)
Absolute value transformation.
factor & exp (void)
Exponential value transformation.
factor & log (void)
Natural logarithm value transformation.
factor & log2 (void)
Logarithm (log 2) value transformation.
factor & log10 (void)
Logarithm (log 10) value transformation.
factor operator+ (const factor &B) const
Sum (const) operation for two factors (A + B).
factor & operator+= (const factor &B)
Sum (non-const) operation for two factors (A += B).
factor operator- (const factor &B) const
Minus (const) operation for two factors (A - B).
factor & operator-= (const factor &B)
Minus (non-const) operation for two factors (A -= B).
factor operator* (const factor &B) const
Multiplication (const) operation for two factors (A * B).
factor & operator*= (const factor &B)
Multiplication (non-const) operation for two factors (A *= B).
factor operator/ (const factor &B) const
Division (const) operation for two factors (A / B).
factor & operator/= (const factor &B)
Division (non-const) operation for two factors (A /= B).
factor operator+ (const value B) const
Sum (const) operation for a factor and a scalar (A + c).
factor & operator+= (const value B)
Sum (non-const) operation for a factor and a scalar (A += c).
factor operator- (const value B) const
Minus (const) operation for a factor and a scalar (A - c).
factor & operator-= (const value B)
Minus (non-const) operation for a factor and a scalar (A -= c).
factor operator* (const value B) const
Multiplication (const) operation for a factor and a scalar (A * c).
factor & operator*= (const value B)
Multiplication (non-const) operation for a factor and a scalar (A *= c).
factor operator/ (const value B) const
Division (const) operation for a factor and a scalar (A / c).
factor & operator/= (const value B)
Division (non-const) operation for a factor and a scalar (A /= c).
factor operator^ (const value B) const
Power (const) operation for a factor and a scalar (A ^ c).
factor & operator^= (const value B)
Power (non-const) operation for a factor and a scalar (A ^= c).
template<typename Function >
factor binaryOp (const factor &B, Function Op) const
Binary operation over factors.
template<typename Function >
factor binaryOp (const value B, Function Op) const
Binary operation between a factor and a scalar.
template<typename Function >
factor & binaryOpIP (const factor &B, Function Op)
Binary operation over factors (in-place).
template<typename Function >
factor & binaryOpIP (const value B, Function Op)
Binary operation between a factor and a scalar (in-place).
factor normalized () const
Normalize the factor (const).
factor & normalize ()
double logpartition () const
Log-partition function.
value entropy (void) const
Entropy function.
factor sum (variable_set const &sum_out) const
value sum () const
factor sum_power (variable_set const &sum_out, value pow) const
factor logsumexp (const variable_set &sum_out) const
factor sigma (size_t n)
Sigma operator.
factor max (variable_set const &sum_out) const
value max () const
factor min (variable_set const &sum_out) const
value min () const
size_t argmax () const
Argmax operation.
size_t argmin () const
Argmin operation.
factor condition (const variable_set &v_rem, vsize v_state) const
Condition on a single variable.
factor slice (const variable_set &v_rem, vsize v_state) const
Condition on a single variable.
factor embed (const variable_set &v) const
Embed extra variables in the factor.
size_t sample () const
Sample the distribution (factor).
vsize draw () const
Sample the distribution (factor).
factor marginal (variable_set const &target) const
Marginal over a set of varibles.
factor marginal (variable_set const &target, const value w) const
Weighted marginal over a set of varibles.
factor maxmarginal (variable_set const &target) const
Max-Marginal over a set of varibles.
factor minmarginal (variable_set const &target) const
Min-Marginal over a set of varibles.
MER_ENUM (Distance, L1, L2, LInf, KL, HPM, MAS, OptGap)
Distance measures.
double distance (factor const &F2, Distance type=Distance::L2) const
Distance between two factors.
double norm (Distance type=Distance::L2) const
Norm of the factor.
MER_ENUM (Decomp, L2, L2_HPM, L2_MAS)
Decomposition methods.
std::vector< factor > decomp_sum (std::vector< variable_set > vlist, factor::Decomp method) const
Decompose a factor into a sum of smaller factors.
std::vector< factor > decomp_prod (std::vector< variable_set > vlist, factor::Decomp method) const
Decompose a factor into a product of factors.
Protected Member Functions
vsize calc_numel () const
Calculate the factor table size.
Static Protected Member Functions
static bool isfinite (double v)
Check if a real value is finite.
static bool isnan (value v)
Check if a real value is not-a-number.
static value infty ()
Return the infinity numerical limit.
Protected Attributes
variable_set v_
Variable list vector (scope).
std::vector< value > t_
Table of values.
Friends
std::ostream & operator<< (std::ostream &out, const factor &f)
Output operator (friend).
Detailed Description
Factor for graphical models.
Table based representation of a factor for graphical models. A factor encodes a potential (sometimes a probability distribution) defined over a subset of discrete random variables, called a scope, and associates each configuration of the variables in the scope with a positive real value (sometimes a probability value). The scope is assumed to be sorted lexicogaphically (e.g., [x1,x2,x3]) Also, the indexing of configurations in the factor table is assumed to be based on the BigEndian convention, namely the first variable in the ordered scope changes the fastest, then the second variable changes its value and so on. For example, consider a factor over binary variables [x1,x2,x3]. The corresponding factor table is indexed as follows (internally):
0: [0,0,0] 4: [0,0,1] 1: [1,0,0] 5: [1,0,1] 2: [0,1,0] 6: [0,1,1] 3: [1,1,0] 7: [1,1,1]
(For converting between source and target orders, use the convert_index class)
Definition at line 62 of file factor.h.
Constructor & Destructor Documentation
merlin::factor::factor (factor const & f) inline
Copy-constructor.
Constructs a copy from an object of the same type.
Definition at line 77 of file factor.h.
Referenced by clone(), and embed().
merlin::factor::factor (const value s = 1.0) inline
Scalar constructor.
Creates a constant factor over an empty set of variables.
Parameters
s The scalar value used to initialize the table (default 1.0)
Definition at line 87 of file factor.h.
merlin::factor::factor (variable_set const & vs, value s = 1.0) inline
Constructor.
Creates a constant factor over a given set of variables.
Parameters
vs The set of variables defining the scope
s The scalar value used to initialize the table (default 1.0)
Definition at line 98 of file factor.h.
References fill(), merlin::variable_set::num_states(), set_dims(), and t_.
merlin::factor::factor (variable_set const & vs, value * t) inline
Constructor.
Creates a factor over a given set of variables and table.
Parameters
vs The input set of variables
t The input table
Definition at line 111 of file factor.h.
References merlin::variable_set::num_states(), set_dims(), t_, and v_.
Member Function Documentation
factor& merlin::factor::abs (void) inline
Absolute value transformation.
Set all table values to their absolute values. This is an in-place trasformation.
Returns
the reference to the transformed factor.
Definition at line 383 of file factor.h.
References t_.
Referenced by distance(), infty(), and norm().
size_t merlin::factor::argmax () const inline
Argmax operation.
Returns
the argument of the maximization operation.
Definition at line 955 of file factor.h.
References t_.
Referenced by merlin::jglp::config(), merlin::graphical_model::max_sequential(), merlin::graphical_model::max_simple(), merlin::bte::update(), merlin::ijgp::update(), and merlin::wmb::update().
size_t merlin::factor::argmin () const inline
Argmin operation.
Returns
the argument of the minimization operation.
Definition at line 964 of file factor.h.
References t_.
template<typename Function > factor merlin::factor::binaryOp (const factor & B, Function Op) const inline
Binary operation over factors.
Functor for binary operations between two factors A and B.
Parameters
B The factor to be combined with
Op The binary operation
Returns
a new factor corresponding to the operation between the input factors A and B.
Definition at line 630 of file factor.h.
References num_states(), t_, and v_.
Referenced by binaryOpIP(), operator*(), operator+(), operator-(), operator/(), and operator^().
template<typename Function > factor merlin::factor::binaryOp (const value B, Function Op) const inline
Binary operation between a factor and a scalar.
Functor for binary operations between a factor A and a scalar B.
Parameters
B The scalar value to be combined with
Op The binary operation
Returns
a new factor corresponding to the operation between the input factor A and scalar value B.
Definition at line 649 of file factor.h.
References binaryOpIP().
template<typename Function > factor& merlin::factor::binaryOpIP (const factor & B, Function Op) inline
Binary operation over factors (in-place).
Functor for in-place binary operations between two factors A and B.
Parameters
B The factor to be combined with
Op The binary operation
Returns
a reference to the modified factor A corresponding to the operation between the input factors A and B.
Definition at line 668 of file factor.h.
References binaryOp(), num_states(), t_, and v_.
Referenced by binaryOp(), operator*=(), operator+=(), operator-=(), operator/=(), and operator^=().
template<typename Function > factor& merlin::factor::binaryOpIP (const value B, Function Op) inline
Binary operation between a factor and a scalar (in-place).
Functor for in-place binary operations between a factor A and a scalar B.
Parameters
B The scalar value to be combined with
Op The binary operation
Returns
a reference to the modified factor A corresponding to the operation between the input factor A and scalar value B.
Definition at line 690 of file factor.h.
References num_states(), and t_.
vsize merlin::factor::calc_numel () const inline protected
Calculate the factor table size.
Compute the actual size of the factor table by multiplying the domain sizes of the variables in its scope.
Returns
the factor table size.
Definition at line 1316 of file factor.h.
References dims(), and nvar().
virtual factor* merlin::factor::clone () inline virtual
Clone from pointer.
Returns
a pointer to the cloned factor.
Definition at line 162 of file factor.h.
References factor().
factor merlin::factor::condition (const variable_set & v_rem, vsize v_state) const inline
Condition on a single variable.
Parameters
v_rem The variable to be conditioned on
v_state The value of the conditioning variable
Returns
a copy of the factor resulting from the conditioning operation.
Definition at line 976 of file factor.h.
References num_states(), t_, and vars().
Referenced by merlin::graphical_model::assert_evidence(), merlin::jglp::config(), merlin::graphical_model::max_sequential(), slice(), merlin::bte::update(), merlin::ijgp::update(), and merlin::wmb::update().
std::vector<factor> merlin::factor::decomp_prod (std::vector< variable_set > vlist, factor::Decomp method) const inline
Decompose a factor into a product of factors.
Parameters
vlist The list of scopes to be used in the decomposition
method The decomposition method
Returns
a vector of new factors representing the decomposition.
Definition at line 1278 of file factor.h.
References decomp_sum(), exp(), and log().
std::vector<factor> merlin::factor::decomp_sum (std::vector< variable_set > vlist, factor::Decomp method) const inline
Decompose a factor into a sum of smaller factors.
Parameters
vlist The list of scopes to be used in the decomposition
method The decomposition method
Returns
a vector of new factors representing the decomposition.
Definition at line 1226 of file factor.h.
References log(), marginal(), max(), min(), numel(), and sum().
Referenced by decomp_prod().
const vsize* merlin::factor::dims () const inline
Variable dimensions.
Returns
the domain sizes (i.e., dimensions) of the variables in the factor's scope.
Definition at line 208 of file factor.h.
References merlin::variable_set::dims(), and v_.
Referenced by calc_numel().
double merlin::factor::distance (factor const & F2, Distance type = Distance::L2) const inline
Distance between two factors.
Compute the distance between the distributions corresponding to the two factors (e.g., KL-distance).
Parameters
F2 The factor to compute the distance from
type The distance measure
Returns
a real value representing the distance between the two factors.
Definition at line 1116 of file factor.h.
References abs(), log(), max(), min(), num_states(), sum(), and vars().
factor merlin::factor::embed (const variable_set & v) const inline
Embed extra variables in the factor.
Parameters
v The set variables to be embeded
Returns
a copy of the factor resulting from embedding the new variables.
Definition at line 1005 of file factor.h.
References factor(), and vars().
value merlin::factor::entropy (void) const inline
Entropy function.
Returns
the value that represents the entropy function of the factor.
Definition at line 811 of file factor.h.
References num_states(), and t_.
Referenced by norm(), and merlin::lbp::obj_entropy().
factor& merlin::factor::exp (void) inline
Exponential value transformation.
Set all table values to their exponential values. This is an in-place trasformation.
Returns
the reference to the transformed factor.
Definition at line 395 of file factor.h.
References t_.
Referenced by decomp_prod(), infty(), logsumexp(), merlin::jglp::run(), and sum_power().
factor& merlin::factor::fill (value v) inline
Fill with constant (in-place).
Set all of the factor table entries to a constant value.
Parameters
v The constant value to be used for filling.
Returns
the reference to the updated factor.
Definition at line 346 of file factor.h.
References t_.
Referenced by factor(), and fill_uniform().
factor& merlin::factor::fill_uniform () inline
Fill with 1/N values.
Set all of the factor table entries to 1/N, where N is the size of the table.
Returns
the reference to the updated factor.
Definition at line 370 of file factor.h.
References fill(), and num_states().
value merlin::factor::get (vsize i) const inline
Access table elements (safe)
Direct access (read-only) to a factor value.
Parameters
i Index of the table element.
Returns
the table element at the given index.
Definition at line 322 of file factor.h.
References t_.
bool merlin::factor::isempty () const inline
Empty factor.
Check if the table of factor values is empty.
Returns
true if the table is empty and false otherwise.
Definition at line 250 of file factor.h.
References t_.
bool merlin::factor::isfinite () const inline
Finite factor.
Check if the table of factor values contains finite real valued entries.
Returns
true if all table entries are finite and false otherwise.
Definition at line 274 of file factor.h.
References num_states(), and t_.
bool merlin::factor::isnan () const inline
Valid factor.
Check if the table of factor values contains valid entries, namely it does not contain any NaN elements.
Returns
true if all table entries are valid and false otherwise.
Definition at line 261 of file factor.h.
References num_states(), and t_.
bool merlin::factor::isscalar () const inline
Scalar (constant) factor.
Check if the factor is a constant (or scalar).
Returns
true if the table size is 1 and false otherwise.
Definition at line 287 of file factor.h.
References numel().
Referenced by merlin::graphical_model::assert_evidence().
factor& merlin::factor::log (void) inline
Natural logarithm value transformation.
Set all table values to their natural log (base e) values. This is an in-place trasformation.
Returns
the reference to the transformed factor.
Definition at line 407 of file factor.h.
References t_.
Referenced by decomp_prod(), decomp_sum(), distance(), infty(), logsumexp(), norm(), merlin::jglp::run(), and sum_power().
factor& merlin::factor::log10 (void) inline
Logarithm (log 10) value transformation.
Set all table values to their log (base 10) values. This is an in-place trasformation.
Returns
the reference to the transformed factor.
Definition at line 431 of file factor.h.
References t_.
Referenced by infty().
factor& merlin::factor::log2 (void) inline
Logarithm (log 2) value transformation.
Set all table values to their log (base 2) values. This is an in-place trasformation.
Returns
the reference to the transformed factor.
Definition at line 419 of file factor.h.
References t_.
Referenced by infty().
double merlin::factor::logpartition () const inline
Log-partition function.
Returns
the value that represents the log-partition function of the factor.
Definition at line 800 of file factor.h.
References sum().
factor merlin::factor::logsumexp (const variable_set & sum_out) const inline
Elimination by summation (log-space).
Sum out (log-space) a subset of variables from the factor's scope.
Parameters
sum_out The set of variables to be summed-out
Returns
a copy of the factor resulting from the variable elimination operation.
Definition at line 882 of file factor.h.
References exp(), log(), marginal(), maxmarginal(), and v_.
Referenced by sum_power().
factor merlin::factor::marginal (variable_set const & target) const inline
Marginal over a set of varibles.
Compute the marginal over a subset of variables by summing out the remaining variables in the factor's scope.
Parameters
target The scope of the marginal
Returns
a copy of the factor resulting from marginalization.
Definition at line 1038 of file factor.h.
References num_states(), t_, v_, and vars().
Referenced by decomp_sum(), logsumexp(), merlin::bte::marg(), merlin::ijgp::marg(), merlin::wmb::marg(), merlin::wmb::match_clusters(), merlin::lbp::obj_entropy(), and sum().
factor merlin::factor::marginal (variable_set const & target, const value w) const inline
Weighted marginal over a set of varibles.
Compute the weighted marginal over a subset of variables by applying the weighted sum operator on the remaining variables in the factor's scope.
Parameters
target The scope of the marginal
w The weight used by the weighted sum operator
Returns
a copy of the factor resulting from marginalization.
Definition at line 1055 of file factor.h.
References infty(), maxmarginal(), num_states(), v_, and vars().
factor merlin::factor::max (variable_set const & sum_out) const inline
Elimination by maximization.
Max out a subset of variables from the factor's scope.
Parameters
sum_out The set of variables to be maxed-out
Returns
a copy of the factor resulting from the variable elimination operation.
Definition at line 911 of file factor.h.
References maxmarginal(), and v_.
Referenced by merlin::bte::backward(), merlin::wmb::backward(), decomp_sum(), distance(), merlin::jglp::elim(), merlin::ijgp::elim(), merlin::bte::forward(), merlin::ijgp::forward(), merlin::wmb::forward(), merlin::graphical_model::get_global_const(), norm(), merlin::jglp::run(), and sigma().
value merlin::factor::max () const inline
Maximum value.
Max out all variables in the factor's scope.
Returns
the maximum value of the factor.
Definition at line 922 of file factor.h.
References infty(), and t_.
Referenced by sum_power().
factor merlin::factor::maxmarginal (variable_set const & target) const inline
Max-Marginal over a set of varibles.
Compute the max-marginal over a subset of variables by maximizing out the remaining variables in the factor's scope.
Parameters
target The scope of the marginal
Returns
a copy of the factor resulting from marginalization.
Definition at line 1077 of file factor.h.
References infty(), num_states(), t_, v_, and vars().
Referenced by logsumexp(), merlin::jglp::marg(), merlin::ijgp::marg(), marginal(), merlin::wmb::match_clusters(), max(), and merlin::graphical_model::max_sequential().
factor merlin::factor::min (variable_set const & sum_out) const inline
Elimination by minimization.
Minmize out a subset of variables from the factor's scope.
Parameters
sum_out The set of variables to be minmized-out
Returns
a copy of the factor resulting from the variable elimination operation.
Definition at line 934 of file factor.h.
References minmarginal(), and v_.
Referenced by decomp_sum(), distance(), and norm().
value merlin::factor::min () const inline
Minimum value.
Minimize out all variables in the factor's scope.
Returns
the minimum value of the factor.
Definition at line 945 of file factor.h.
References infty(), and t_.
Referenced by sum_power().
factor merlin::factor::minmarginal (variable_set const & target) const inline
Min-Marginal over a set of varibles.
Compute the min-marginal over a subset of variables by minimizing out the remaining variables in the factor's scope.
Parameters
target The scope of the marginal
Returns
a copy of the factor resulting from marginalization.
Definition at line 1093 of file factor.h.
References infty(), MER_ENUM(), num_states(), t_, v_, and vars().
Referenced by min().
double merlin::factor::norm (Distance type = Distance::L2) const inline
Norm of the factor.
Compute the norm of the factor (e.g., L2 norm).
Parameters
type The distance measure
Returns
a real value representing the norm of the factor.
Definition at line 1188 of file factor.h.
References abs(), entropy(), log(), max(), MER_ENUM(), min(), and sum().
factor& merlin::factor::normalize () inline
Normalize the factor (non-const)
Returns
a reference to the modified factor as a result of normalization.
Definition at line 788 of file factor.h.
References sum().
Referenced by normalized().
factor merlin::factor::normalized () const inline
Normalize the factor (const).
Returns
a copy of the factor resulted from the normalization.
Definition at line 777 of file factor.h.
References normalize().
size_t merlin::factor::num_states () const inline
Size of the factor's table.
Returns
the size of the table storing the factor values. It is equal to the product of the domain sizes of the variables in the factor's scope.
Definition at line 228 of file factor.h.
References t_.
Referenced by binaryOp(), binaryOpIP(), condition(), distance(), entropy(), fill_uniform(), isfinite(), isnan(), marginal(), maxmarginal(), minmarginal(), and sample().
size_t merlin::factor::numel () const inline
Size of the factor's table.
Returns
the size of the table storing the factor values. It is equal to the product of the domain sizes of the variables in the factor's scope.
Definition at line 238 of file factor.h.
References t_.
Referenced by decomp_sum(), isscalar(), and merlin::graphical_model::write().
const size_t merlin::factor::nvar () const inline
Size of the factor's scope.
Returns
the number of variables in the factor's scope.
Definition at line 180 of file factor.h.
References merlin::variable_set::nvar(), and v_.
Referenced by merlin::factor_graph::add_factor(), calc_numel(), merlin::graphical_model::largest(), merlin::jglp::run(), merlin::jglp::score(), merlin::graphical_model::smallest(), and merlin::graphical_model::write().
factor& merlin::factor::operator= (factor const & rhs) inline
Assignment operator.
The operator performs a deep copy of the object.
Parameters
rhs A factor object of the same type
Returns
a reference to the current factor whose content was copied from the factor received as argument.
Definition at line 133 of file factor.h.
References set_dims(), t_, and v_.
value merlin::factor::operator[] (vsize v) const inline
Access table elements (const)
Direct access (read-only) to a factor value.
Parameters
v Index of the table element.
Returns
the table element at the given index.
Definition at line 300 of file factor.h.
References t_.
value& merlin::factor::operator[] (vsize v) inline
Rewrite table elements (non-const)
Direct access (read and write) to a factor value.
Parameters
v Index of the table element.
Returns
the non-const reference to table element at the given index.
Definition at line 311 of file factor.h.
References t_.
factor& merlin::factor::randomize () inline
Fill with random values in [0,1).
Set all of the factor table entries to random values drawn uniformly at random between 0 and 1.
Returns
the reference to the updated factor.
Definition at line 358 of file factor.h.
References t_.
void merlin::factor::set (vsize i, value v) inline
Rewrite table elements (safe)
Re-write a factor value.
Parameters
i Index of the table element.
v New value to be written in the table.
Definition at line 333 of file factor.h.
References t_.
factor merlin::factor::sigma (size_t n) inline
Sigma operator.
The special sigma operator used by weighed mini-buckets for marginal MAP queries.
Definition at line 897 of file factor.h.
References max().
Referenced by merlin::wmb::backward().
factor merlin::factor::slice (const variable_set & v_rem, vsize v_state) const inline
Condition on a single variable.
Parameters
v_rem The variable to be conditioned on
v_state The value of the conditioning variable
Returns
a copy of the factor resulting from the conditioning operation.
Definition at line 995 of file factor.h.
References condition().
Referenced by merlin::gibbs::run().
factor merlin::factor::sum (variable_set const & sum_out) const inline
Elimination by summation.
Sum out a subset of variables from the factor's scope.
Parameters
sum_out The set of variables to be summed-out
Returns
a copy of the factor resulting from the variable elimination operation.
Definition at line 834 of file factor.h.
References marginal(), and v_.
Referenced by merlin::lbp::accept_incoming(), merlin::bte::backward(), merlin::wmb::backward(), merlin::lbp::calc_belief(), decomp_sum(), distance(), merlin::ijgp::elim(), merlin::bte::forward(), merlin::ijgp::forward(), merlin::wmb::forward(), merlin::lbp::init(), and norm().
value merlin::factor::sum () const inline
Eliminate all variables by summation.
Sum out all variables in the factor's scope.
Returns
a constant value resulting from the variable elimination operation.
Definition at line 845 of file factor.h.
References t_.
Referenced by distance(), logpartition(), normalize(), sample(), and sum_power().
factor merlin::factor::sum_power (variable_set const & sum_out, value pow) const inline
Elimination by weighted summation.
Weighted-Sum out a subset of variables from the factor's scope.
Parameters
sum_out The set of variables to be summed-out
pow The exponent of the weighted sum operator
Returns
a copy of the factor resulting from the weighted variable elimination operation.
Definition at line 857 of file factor.h.
References exp(), infty(), log(), logsumexp(), max(), min(), and sum().
Referenced by merlin::bte::elim(), merlin::wmb::elim(), and merlin::wmb::forward().
void merlin::factor::swap (factor & f) inline
Swap the object contents.
Exchange the contents of "this" and the factor received as input.
Parameters
f The factor to exchange the content of
Definition at line 150 of file factor.h.
References merlin::variable_set::swap(), t_, and v_.
const value* merlin::factor::table () const inline
Table of factor values.
Returns
the table containing the factor values. Each value in the table corresponds to a particular configuration of the scope variables.
Definition at line 218 of file factor.h.
References t_.
Referenced by merlin::graphical_model::assert_evidence().
const variable_set& merlin::factor::variables () const inline
Scope of the factor.
Returns
the scope (as set of variable ids) of the factor.
Definition at line 198 of file factor.h.
References v_.
const variable_set& merlin::factor::vars () const inline
Scope of the factor.
Returns
the scope (as set of variable ids) of the factor.
Definition at line 189 of file factor.h.
References v_.
Referenced by merlin::factor_graph::add_factor(), merlin::graphical_model::add_factor(), merlin::factor_graph::adjacent_vars(), merlin::graphical_model::assert_evidence(), condition(), merlin::jglp::config(), distance(), embed(), marginal(), merlin::graphical_model::markov_blanket(), merlin::graphical_model::max_sequential(), maxmarginal(), minmarginal(), merlin::gibbs::run(), merlin::jglp::score(), merlin::factor_graph::span_tree(), merlin::lbp::update_outgoing(), and merlin::graphical_model::write().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const factor & f) friend
Output operator (friend).
Write the (formatted) content of the factor to an output stream.
Parameters
out The output stream
f The Factor to be written out
Returns
a reference to the modified output stream containing the content of the factor received as input.
Definition at line 1297 of file factor.h.
The documentation for this class was generated from the following file:
src/include/factor.h