Merlin: merlin::wmb Class Reference
merlin::wmb Class Reference
#include <wmb.h>
Classes
struct Pair
Helper class for pairs of sorted indices.
Public Types
typedef graphical_model::findex findex
Factor index.
typedef graphical_model::vindex vindex
Variable index.
typedef graphical_model::flist flist
Collection of factor indices.
Public Types inherited from merlin::graphical_model
typedef size_t findex
Factor index.
typedef size_t vindex
Variable index.
typedef set< findex > flist
Collection of factor indices.
Public Types inherited from merlin::graph
typedef edge_id::index index
Basic indexing type for the graph.
Public Member Functions
wmb ()
Default constructor.
wmb (const graphical_model &gm)
Constructor with a graphical model.
virtual wmb * clone () const
Clone the algorithm.
double ub () const
Upper bound on the optimal value.
double lb () const
Lower bound on the optimal value.
std::vector< size_t > best_config () const
Best configuration.
double logZ () const
Log value of the partition function.
double logZub () const
Upper bound on the log partition function.
double logZlb () const
Lower bound on the log partition function.
const factor & belief (size_t f) const
Belief associated with a node of the graph.
const factor & belief (variable v) const
Belief associated with a particular variable.
const factor & belief (variable_set vs) const
Belief associated with a set of variables.
const vector< factor > & beliefs () const
Beliefs associated with the variables.
const graphical_model & get_gm_orig () const
Get the original graphical model.
void write_solution (const char *file_name, const std::map< size_t, size_t > &evidence, const std::map< size_t, size_t > &old2new, const graphical_model &orig, const bool first=true)
Write the solution to the output file.
virtual void run ()
Run the weighted mini-buckets algorithm.
MER_ENUM (Task, PR, MAR, MAP, MMAP)
Inference tasks supported.
MER_ENUM (Property, iBound, Order, Task, Iter, Debug, OrderIter)
Properties of the algorithm.
void set_ibound (size_t i)
Set the mini-bucket i-bound parameter.
size_t get_ibound () const
Get the mini-bucket i-bound parameter.
void set_var_types (const vector< bool > &var_types)
Set the variable types.
const vector< bool > & get_var_types () const
Get the variable types.
void set_order (const variable_order_t &ord)
Set the variable order.
void set_order_method (graphical_model::OrderMethod method)
Set the variable order method.
const variable_order_t & get_order ()
Get the variable order.
const std::vector< vindex > & get_pseudo_tree ()
Get the pseudo tree.
void set_pseudo_tree (const vector< vindex > &p)
Set the pseudo tree.
void set_query (const std::vector< vindex > &q)
Set the query (MAP) variables.
const std::vector< vindex > & get_query ()
Get the query (MAP) variables.
void set_graphical_model (const graphical_model &gm)
Set the graphical model.
void set_graphical_model (const vector< factor > &fs)
Set the graphical model from a list of factors.
virtual void set_properties (std::string opt=std::string())
Set the properties of the algorithm.
factor elim (const factor &F, const variable_set &vs, const double w)
Eliminate a set of variables from a factor.
factor marg (const factor &F, const variable_set &vs, const double w)
Compute the weighted marginal over a set of variables.
double score (const vector< variable_set > &fin, const variable &VX, size_t i, size_t j)
Scoring function for bucket aggregation.
void init ()
Initialize the weighted mini-buckets algorithm.
factor calc_belief (findex a)
Compute the belief of a cluster.
factor incoming (findex a, size_t i)
Compute the belief of a cluster excluding an incoming message.
factor incoming (findex a)
Compute the belief of a cluster excluding backward messages.
void forward (double step)
Forward (top-down) message passing with moment matching between the clusters of a bucket.
void backward (size_t iter)
Backward (bottom-up) message passing.
void match_clusters (size_t x, double step)
Perform moment-matching between the clusters of a variable.
void tighten (size_t nIter, double stopTime=-1, double stopObj=-1)
Iterative tightening of the upper bound.
void update ()
Update the beliefs (marginals or max-marginals)
Public Member Functions inherited from merlin::graphical_model
graphical_model ()
Creates an empty graphical model.
graphical_model (const graphical_model &gm)
Creates a graphical model by copying an existing one.
graphical_model & operator= (const graphical_model &gm)
Assignment operator (deep copy).
virtual graphical_model * clone ()
Clone the graphical model.
graphical_model (std::vector< factor > fs)
Constructor from a list of factors.
template<class InputIterator >
graphical_model (InputIterator first, InputIterator last)
Creates a graphical model from input iterators.
virtual ~graphical_model ()
Destroys the graphical model.
void read (const char *file_name)
Read the graphical model from a file in the UAI format.
void write (const char *file_name)
Write the graphical model to a file using the UAI format.
bool is_markov ()
Check if graphical model is a Markov or a Bayes net.
std::vector< factor > assert_evidence (const char *file_name, std::map< size_t, size_t > &evidence, std::map< size_t, size_t > &old_to_new)
Assert evidence into the graphical model.
std::vector< factor > assert_evidence (const std::map< size_t, size_t > &evidence, std::map< size_t, size_t > &old_to_new)
Assert evidence into the graphical model.
size_t nvar () const
Return the number of variables in the model.
variable var (vindex i) const
Convert a variable index to Var object.
size_t num_factors () const
Return the number of factors in the model.
const factor & get_factor (findex idx) const
Accessor for a factor.
const std::vector< factor > & get_factors () const
Accessor for the factor container.
const flist & with_variable (const variable &v) const
Factors depending on a variable.
flist with_variable_set (const variable_set &vs) const
Union of factors depending on a set of variables.
flist intersects (const variable_set &vs) const
Intersection of factors depending on a set of variables.
flist contains (const variable &v) const
Factors depending on a variable.
flist contains (const variable_set &vs) const
Union of factors depending on a set of variables.
flist contained_by (const variable_set &vs) const
Factors contained by a set of variables.
variable_set markov_blanket (const variable &v) const
Markov blanket of a variable.
variable_set markov_blanket (const variable_set &vs) const
Markov blanket of a set of variables.
std::vector< variable_set > mrf () const
Full adjacency matrix.
virtual findex add_factor (const factor &F)
Add a new factor to the model.
virtual void remove_factor (findex idx)
Remove a factor from the model.
void clear_factors ()
Remove all factors.
findex smallest (const flist &fl)
Find the factor with the smallest scope.
findex largest (const flist &fl)
Find the factor with the largest scope.
bool is_binary () const
Check if a binary model.
bool is_pairwise () const
Check if a pairwise model.
factor joint (size_t maxsize=0) const
Directly calculate joint distribution function.
size_t induced_width (const variable_order_t &order) const
Find the induced width (complexity) of an elimination order.
std::pair< size_t, size_t > pseudo_tree_size (const variable_order_t &order) const
Find induced width and pseudo tree height of an elimination order.
std::vector< vindex > pseudo_tree (const variable_order_t &order) const
Find the pseudo tree corresponding to an elimination order.
MER_ENUM (OrderMethod, MinFill, WtMinFill, MinWidth, WtMinWidth, Random)
Variable ordering methods.
variable_order_t order (OrderMethod ord_type) const
Find a variable elimination order.
variable_order_t order2 (OrderMethod ord_type) const
Find a variable elimination order.
variable_order_t order2 (OrderMethod ord_type, std::vector< bool > var_types) const
Find a constrained variable elimination order.
variable_order_t order (OrderMethod ord_type, std::vector< bool > var_types) const
Find a constrained variable elimination order.
void improve_order (OrderMethod ord_type, double &old_score, variable_order_t &old_order) const
Look for a better order iteratively.
void insert (std::vector< flist > &adj, findex idx, const variable_set &vs)
Add the scope of a factor to the adjacency list.
void erase (std::vector< flist > &adj, findex idx, const variable_set &vs)
Remove the scope of a factor from the adjacency list.
std::vector< size_t > max_simple ()
Find smallest factor with each variable and select its optimum.
std::vector< size_t > max_sequential (const variable_order_t &order)
Find maxmarginal for variable and select optimum given those so far.
double logP (const std::vector< size_t > &config)
Compute the log-probability of a particular (complete) configuration.
double get_global_const () const
Return the constant resulted from asserting evidence in the model.
Public Member Functions inherited from merlin::graph
graph (size_t n=0)
Constructs a graph with n vertices and 0 edges.
~graph ()
Destroys the graph.
index add_node ()
Add a node to the graph.
void remove_node (index i)
Remove a node from the graph.
size_t num_nodes ()
Return the number of nodes.
size_t num_edges ()
Return the number of edges.
const edge_id & add_edge (index i, index j)
Add an edge to the graph.
void remove_edge (index i, index j)
Remove an edge from the graph.
void clear ()
Clear the graph by removing all nodes and edges.
void clear_edges ()
Remove all edges.
const edge_id & edge (index i, index j) const
Return the edge (if any) between two nodes.
const set< edge_id > & neighbors (index i) const
Return the neighbors of a node (ie, adjacency list).
const edge_id & edge (index eij) const
Return an edge (by its index).
const std::vector< edge_id > & edges () const
Return the edges of the graph.
Public Member Functions inherited from merlin::algorithm
algorithm ()
Constructs an empty algorithm.
virtual ~algorithm ()
Destructs the algorithm.
void set_stop_iter (double d)
Set the number of iterations.
void set_stop_obj (double d)
Set the minumum objective change before stopping.
void set_stop_msg (double d)
Set the minimum ammount a message changes before stopping.
Protected Attributes
graphical_model m_gmo
Original graphical model.
Task m_task
Inference task.
OrderMethod m_order_method
Variable ordering method.
size_t m_order_iter
Number of iterations for ordering heuristic.
size_t m_ibound
Mini-bucket i-bound.
double m_log_z
Log partition function value.
variable_order_t m_order
Variable order.
std::vector< vindex > m_parents
Pseudo tree.
vector< bool > m_var_types
Variable types (true if MAX, false if SUM)
vector< factor > m_beliefs
Marginals.
std::vector< vindex > m_best_config
MAP assignment.
std::vector< vindex > m_query
MAX variables for the MMAP task.
size_t m_num_iter
Number of iterations to be executed.
double m_lb
Lower bound (ie, value of MAP assignment)
Protected Attributes inherited from merlin::graphical_model
std::vector< factor > m_factors
Collection of all factors in the model.
bool m_markov
Markov or Bayes network. Default is true (Markov)
Protected Attributes inherited from merlin::graph
std::stack< index > m_vvacant
List of available vertex ids.
std::stack< index > m_evacant
List of available edge ids.
Protected Attributes inherited from merlin::algorithm
double m_stop_iter
Stopping criteria (iterations)
double m_stop_obj
Stopping criteria (objective change)
double m_stop_msg
Stopping criteria (message change)
double m_start_time
Start time.
Additional Inherited Members
Public Attributes inherited from merlin::graph
std::vector< set< edge_id > > m_adj
Look up EdgeID info by adj[i][jj] (jj = position of j).
std::vector< edge_id > m_edges
Look up EdgeID info by edges[eij] (edge index).
Protected Member Functions inherited from merlin::graphical_model
size_t _vindex (const variable &v) const
Look up the index of a variable.
flist & _with_variable (const variable &v)
Mutable accessor of adjacency.
void fixup ()
Internal function for ensuring consistency of the model.
double order_score (const std::vector< variable_set > &adj, size_t i, OrderMethod kOType) const
Compute the score of a variable for the elimination order.
variable_order_t order_random () const
Create a random elimination order.
Detailed Description
Weighted Mini-Buckets (WMB)
Tasks supported: PR, MAR, MAP, MMAP
WMB generalizes the classical MBE by replacing the sum operator with a weighted sum operator, and thus it uses Holder's inequality to derive an upper bound on the log partition function, MAP or Marginal MAP value. WMB also uses an iterative cost-shifting scheme that matches marginals (weighted or max) in order to tighten the upper-bound. Tightening is not guaranteed in general, but it typically happens in practice.
Definition at line 46 of file wmb.h.
Member Function Documentation
const factor& merlin::wmb::belief (size_t i) const inline virtual
Belief associated with a node of the graph.
Returns
the belief associated with a node of the graph. Nodes correspond typically to variables. The belied is a function represented by the Factor class.
Parameters
i The index of the node in the graph (from 0)
Implements merlin::algorithm.
Definition at line 100 of file wmb.h.
References m_beliefs.
Referenced by run(), and write_solution().
const factor& merlin::wmb::belief (variable v) const inline virtual
Belief associated with a particular variable.
Parameters
v The variable to compute the belief of
Returns
the belief associated with a particular variable in the graphical model. The belief is a function represented by the Factor class.
Implements merlin::algorithm.
Definition at line 103 of file wmb.h.
References m_beliefs.
const factor& merlin::wmb::belief (variable_set vs) const inline virtual
Belief associated with a set of variables.
Parameters
vs The set of variables to compute the belief of
Returns
the belief associated with a set of variables in the graphical model. The belief is a function represented by the Factor class.
Implements merlin::algorithm.
Definition at line 106 of file wmb.h.
const vector<factor>& merlin::wmb::beliefs () const inline virtual
Beliefs associated with the variables.
Returns
the beliefs associated with the variables in the graphical model (one belief for each of the variables). The output vector is indexed by the same indexes used for the variables.
Implements merlin::algorithm.
Definition at line 109 of file wmb.h.
References m_beliefs.
std::vector<size_t> merlin::wmb::best_config () const inline virtual
Best configuration.
Returns
a vector containing the best configuration of the variables (i.e., variable value assignments) found so far. It is specific to optimization tasks (e.g., MAP, Marginal MAP).
Implements merlin::algorithm.
Definition at line 85 of file wmb.h.
References m_best_config.
factor merlin::wmb::calc_belief (findex a) inline
Compute the belief of a cluster.
Parameters
a The index of the cluster
Returns
the factor representing the belief of the cluster.
Definition at line 859 of file wmb.h.
References merlin::graphical_model::m_factors.
Referenced by backward(), forward(), match_clusters(), and update().
virtual wmb* merlin::wmb::clone () const inline virtual
Clone the algorithm.
Returns
the pointer to the new object containing the cloned algorithm.
Implements merlin::algorithm.
Definition at line 73 of file wmb.h.
References wmb().
factor merlin::wmb::elim (const factor & F, const variable_set & vs, const double w) inline
Eliminate a set of variables from a factor.
Parameters
F The reference of the factor to eliminate from
vs The set of variables to be eliminated
w The weight of the weighted elimination operator
Returns
the factor resulted from eliminating the set of variables.
Definition at line 452 of file wmb.h.
References merlin::factor::sum_power().
factor merlin::wmb::incoming (findex a, size_t i) inline
Compute the belief of a cluster excluding an incoming message.
Parameters
a The index of the cluster to compute the belief of
i The index of the cluster sending the incoming message
Returns
the factor representing the belief of cluster a excluding the incoming message from i to a.
Definition at line 889 of file wmb.h.
References merlin::graphical_model::m_factors.
Referenced by forward(), and update().
factor merlin::wmb::incoming (findex a) inline
Compute the belief of a cluster excluding backward messages.
Parameters
a The index of the cluster to compute the belief of
Returns
the factor representing the belief of cluster a excluding the backward messages from clusters below a.
Definition at line 911 of file wmb.h.
References merlin::graphical_model::m_factors.
double merlin::wmb::lb () const inline virtual
Lower bound on the optimal value.
Returns
a lower bound on the optimal value defined by the inference task if available.
Implements merlin::algorithm.
Definition at line 82 of file wmb.h.
double merlin::wmb::logZ () const inline virtual
Log value of the partition function.
Returns
an estimate the log parition function. If the inference algorithm is an exact one then the return value is the exact log value of the partition function.
Implements merlin::algorithm.
Definition at line 89 of file wmb.h.
References m_log_z.
Referenced by write_solution().
double merlin::wmb::logZlb () const inline virtual
Lower bound on the log partition function.
Returns
a lower bound on the log value of the parition function.
Implements merlin::algorithm.
Definition at line 95 of file wmb.h.
References m_log_z.
double merlin::wmb::logZub () const inline virtual
Upper bound on the log partition function.
Returns
an upper bound on the log value of the parition function. Most inference algorithms implemented in merlin support upper bounds on the log partition function.
Implements merlin::algorithm.
Definition at line 92 of file wmb.h.
References m_log_z.
factor merlin::wmb::marg (const factor & F, const variable_set & vs, const double w) inline
Compute the weighted marginal over a set of variables.
Parameters
F The reference of the factor to marginalize over
vs The set of variables representing the scope of the marginal
w The weight of the weighted elimination operator
Returns
the factor representing the weighted marginal over the set of variables.
Definition at line 463 of file wmb.h.
References merlin::factor::marginal().
Referenced by update().
double merlin::wmb::score (const vector< variable_set > & fin, const variable & VX, size_t i, size_t j) inline
Scoring function for bucket aggregation.
Parameters
fin The set of factor scopes containing the pair (i,j) to be aggregated
VX The bucket variable
i The index of first scope
j The index of the second pair
Returns
the score that corresponds to aggregating the two scopes. It returns -3 if unable to combine, -1 for scope only aggregation, and otherwise a positive double score.
Definition at line 478 of file wmb.h.
References m_ibound, and merlin::variable_set::nvar().
Referenced by init().
virtual void merlin::wmb::set_properties (std::string opt = std::string()) inline virtual
Set the properties of the algorithm.
Parameters
opt The string containing comma separated property value pairs
Definition at line 408 of file wmb.h.
References m_num_iter, m_order, m_order_iter, m_order_method, m_parents, m_task, and set_ibound().
Referenced by Merlin::run(), and wmb().
double merlin::wmb::ub () const inline virtual
Upper bound on the optimal value.
Returns
an upper bound on the optimal value defined by the inference task. It is specific to optimization tasks such as MAP and Marginal MAP inference.
Implements merlin::algorithm.
Definition at line 79 of file wmb.h.
References m_log_z.
void merlin::wmb::write_solution (const char * file_name, const std::map< size_t, size_t > & evidence, const std::map< size_t, size_t > & old2new, const graphical_model & orig, const bool first = true) inline
Write the solution to the output file.
Parameters
filename The output file name
evidence The evidence variable value pairs
old2new The mapping between old and new variable indexing
orig The graphical model prior to asserting evidence
Definition at line 127 of file wmb.h.
References belief(), merlin::graphical_model::get_global_const(), logZ(), m_best_config, m_log_z, m_query, m_task, m_var_types, merlin::graphical_model::nvar(), merlin::variable::states(), and merlin::graphical_model::var().
Referenced by Merlin::run().
The documentation for this class was generated from the following file:
src/include/wmb.h