Merlin: merlin::algorithm Class Reference
merlin::algorithm Class Reference abstract
Interface for all inference algorithms.
#include <algorithm.h>
Public Member Functions
algorithm ()
Constructs an empty algorithm.
virtual algorithm * clone () const =0
Clone the current algorithm interface.
virtual ~algorithm ()
Destructs the algorithm.
virtual void init ()=0
Inialize the algorithm.
virtual void run ()=0
Run the algorithm.
virtual double logZ () const =0
Log value of the partition function.
virtual double logZub () const =0
Upper bound on the log partition function.
virtual double logZlb () const =0
Lower bound on the log partition function.
virtual double ub () const =0
Upper bound on the optimal value.
virtual double lb () const =0
Lower bound on the optimal value.
virtual std::vector< size_t > best_config () const =0
Best configuration.
virtual const factor & belief (size_t i) const =0
Belief associated with a node of the graph.
virtual const factor & belief (variable v) const =0
Belief associated with a particular variable.
virtual const factor & belief (variable_set vs) const =0
Belief associated with a set of variables.
virtual const std::vector< factor > & beliefs () const =0
Beliefs associated with the variables.
void set_stop_iter (double d)
Set the number of iterations.
void set_stop_obj (double d)
Set the minumum objective change before stopping.
void set_stop_msg (double d)
Set the minimum ammount a message changes before stopping.
Protected Attributes
double m_stop_iter
Stopping criteria (iterations)
double m_stop_obj
Stopping criteria (objective change)
double m_stop_msg
Stopping criteria (message change)
double m_start_time
Start time.
Detailed Description
Interface for all inference algorithms.
The class provides the functional interface for any probabilistic inference algorithm. It is a pure virtual class and therefore it should be implemented by a concrete (derived) inference algorithm (e.g., wmb).
Definition at line 47 of file algorithm.h.
Member Function Documentation
const factor & merlin::algorithm::belief (size_t i) const pure virtual
Belief associated with a node of the graph.
Returns
the belief associated with a node of the graph. Nodes correspond typically to variables. The belied is a function represented by the Factor class.
Parameters
i The index of the node in the graph (from 0)
Implemented in merlin::gibbs, merlin::ijgp, merlin::jglp, merlin::lbp, merlin::wmb, and merlin::bte.
Referenced by ~algorithm().
virtual const factor& merlin::algorithm::belief (variable v) const pure virtual
Belief associated with a particular variable.
Parameters
v The variable to compute the belief of
Returns
the belief associated with a particular variable in the graphical model. The belief is a function represented by the Factor class.
Implemented in merlin::gibbs, merlin::ijgp, merlin::jglp, merlin::lbp, merlin::wmb, and merlin::bte.
virtual const factor& merlin::algorithm::belief (variable_set vs) const pure virtual
Belief associated with a set of variables.
Parameters
vs The set of variables to compute the belief of
Returns
the belief associated with a set of variables in the graphical model. The belief is a function represented by the Factor class.
Implemented in merlin::gibbs, merlin::ijgp, merlin::jglp, merlin::lbp, merlin::wmb, and merlin::bte.
const std::vector< Factor > & merlin::algorithm::beliefs () const pure virtual
Beliefs associated with the variables.
Returns
the beliefs associated with the variables in the graphical model (one belief for each of the variables). The output vector is indexed by the same indexes used for the variables.
Implemented in merlin::gibbs, merlin::ijgp, merlin::jglp, merlin::lbp, merlin::wmb, and merlin::bte.
Referenced by ~algorithm().
virtual std::vector<size_t> merlin::algorithm::best_config () const pure virtual
Best configuration.
Returns
a vector containing the best configuration of the variables (i.e., variable value assignments) found so far. It is specific to optimization tasks (e.g., MAP, Marginal MAP).
Implemented in merlin::gibbs, merlin::lbp, merlin::ijgp, merlin::jglp, merlin::bte, and merlin::wmb.
Referenced by ~algorithm().
virtual algorithm* merlin::algorithm::clone () const pure virtual
Clone the current algorithm interface.
Returns
a pointer to the object storing the copy of the algorithm.
Implemented in merlin::lbp, merlin::ijgp, merlin::jglp, merlin::bte, merlin::wmb, and merlin::gibbs.
Referenced by algorithm().
virtual void merlin::algorithm::init () pure virtual
Inialize the algorithm.
The initialization step must be performed before running the algorithm.
Implemented in merlin::wmb, merlin::ijgp, merlin::bte, merlin::jglp, merlin::lbp, and merlin::gibbs.
Referenced by ~algorithm().
virtual double merlin::algorithm::lb () const pure virtual
Lower bound on the optimal value.
Returns
a lower bound on the optimal value defined by the inference task if available.
Implemented in merlin::gibbs, merlin::lbp, merlin::ijgp, merlin::jglp, merlin::bte, and merlin::wmb.
Referenced by ~algorithm().
virtual double merlin::algorithm::logZ () const pure virtual
Log value of the partition function.
Returns
an estimate the log parition function. If the inference algorithm is an exact one then the return value is the exact log value of the partition function.
Implemented in merlin::gibbs, merlin::lbp, merlin::ijgp, merlin::jglp, merlin::bte, and merlin::wmb.
Referenced by ~algorithm().
virtual double merlin::algorithm::logZlb () const pure virtual
Lower bound on the log partition function.
Returns
a lower bound on the log value of the parition function.
Implemented in merlin::gibbs, merlin::lbp, merlin::ijgp, merlin::jglp, merlin::bte, and merlin::wmb.
Referenced by ~algorithm().
virtual double merlin::algorithm::logZub () const pure virtual
Upper bound on the log partition function.
Returns
an upper bound on the log value of the parition function. Most inference algorithms implemented in merlin support upper bounds on the log partition function.
Implemented in merlin::gibbs, merlin::lbp, merlin::ijgp, merlin::jglp, merlin::bte, and merlin::wmb.
Referenced by ~algorithm().
virtual void merlin::algorithm::run () pure virtual
Run the algorithm.
Solves a probabilistic inference task.
Implemented in merlin::jglp, merlin::lbp, merlin::wmb, merlin::bte, merlin::ijgp, and merlin::gibbs.
Referenced by ~algorithm().
void merlin::algorithm::set_stop_iter (double d) inline
Set the number of iterations.
Stop when d*(# factors) updates have been done.
Definition at line 188 of file algorithm.h.
References m_stop_iter.
Referenced by merlin::lbp::set_properties().
void merlin::algorithm::set_stop_msg (double d) inline
Set the minimum ammount a message changes before stopping.
Stop when message updates are less than d.
Parameters
d The tolerated message update
Definition at line 208 of file algorithm.h.
References m_stop_msg.
Referenced by merlin::lbp::set_properties().
void merlin::algorithm::set_stop_obj (double d) inline
Set the minumum objective change before stopping.
Stop when objective change is less than d.
Parameters
d The objective change
Definition at line 198 of file algorithm.h.
References m_stop_obj.
Referenced by merlin::lbp::set_properties().
virtual double merlin::algorithm::ub () const pure virtual
Upper bound on the optimal value.
Returns
an upper bound on the optimal value defined by the inference task. It is specific to optimization tasks such as MAP and Marginal MAP inference.
Implemented in merlin::gibbs, merlin::lbp, merlin::ijgp, merlin::jglp, merlin::bte, and merlin::wmb.
Referenced by ~algorithm().
The documentation for this class was generated from the following file:
src/include/algorithm.h