Merlin: merlin::lbp Class Reference
merlin::lbp Class Reference
#include <lbp.h>
Public Types
typedef factor_graph::findex findex
Factor index.
typedef factor_graph::vindex vindex
Variable index.
typedef factor_graph::flist flist
Collection of factor indices.
Public Types inherited from merlin::factor_graph
typedef graphical_model::findex findex
Factor index.
typedef graphical_model::vindex vindex
Variable index.
typedef graphical_model::flist flist
Collection of factor indices.
Public Types inherited from merlin::graphical_model
typedef size_t findex
Factor index.
typedef size_t vindex
Variable index.
typedef set< findex > flist
Collection of factor indices.
Public Types inherited from merlin::graph
typedef edge_id::index index
Basic indexing type for the graph.
Public Member Functions
lbp ()
Constructs algorithm instance over an empty factor graph.
lbp (const factor_graph &fg)
Constructs algorithm instance from a copy of a factor graph.
lbp (std::vector< factor > fs)
Constructs algorithm instance from a list of factors.
template<class InputIterator >
lbp (InputIterator f, InputIterator l)
Constructs algorithm instance from input iterators.
virtual lbp * clone () const
Clone the algorithm object.
merlin::factor & bel (size_t f)
Mutable accessor to a belief.
const factor & belief (size_t f) const
Belief associated with a node of the graph.
const factor & belief (variable v) const
Belief associated with a particular variable.
const factor & belief (variable_set vs) const
Belief associated with a set of variables.
const std::vector< factor > & beliefs () const
Beliefs associated with the variables.
double lb () const
Lower bound on the optimal value.
double ub () const
Upper bound on the optimal value.
std::vector< index > best_config () const
Best configuration.
double logZ () const
Log value of the partition function.
double logZub () const
Upper bound on the log partition function.
double logZlb () const
Lower bound on the log partition function.
MER_ENUM (Schedule, Fixed, Random, Flood, Priority)
Types of propagation schedules.
MER_ENUM (Property, Schedule, Distance, StopIter, StopObj, StopMsg, Debug)
Properties of the algorithm.
virtual void set_properties (std::string opt=std::string())
Set the properties of the algorithm.
void init ()
Initialize the LBP algorithm.
void write_solution (const char *file_name, const std::map< size_t, size_t > &evidence, const std::map< size_t, size_t > &old2new, const graphical_model &orig)
Write the solution to the output file.
void run ()
Run the algorithm.
Public Member Functions inherited from merlin::algorithm
algorithm ()
Constructs an empty algorithm.
virtual ~algorithm ()
Destructs the algorithm.
void set_stop_iter (double d)
Set the number of iterations.
void set_stop_obj (double d)
Set the minumum objective change before stopping.
void set_stop_msg (double d)
Set the minimum ammount a message changes before stopping.
Public Member Functions inherited from merlin::factor_graph
factor_graph ()
Default constructor.
factor_graph (const factor_graph &fg)
Copy constructor.
factor_graph (std::vector< factor > fs)
Constructor.
template<class InputIterator >
factor_graph (InputIterator first, InputIterator last)
Constructor.
virtual factor_graph * clone ()
Clone the factor graph.
findex add_factor (const factor &F)
Add a new factor to the graphical model.
void remove_factor (findex f)
Remove a factor from the model.
findex local_factor (vindex i) const
Retrieve the factor index corresponding to a variable node.
findex local_factor (variable v) const
Retrieve the factor index corresponding to a variable node.
bool is_var_node (findex i) const
Check if a factor is a variable node in the factor graph.
flist adjacent_factors (variable v) const
Retrieve the factors adjacent to a variable node in the factor graph.
flist adjacent_factors (vindex v) const
Retrieve the factors adjacent to a variable node in the factor graph.
variable_set adjacent_vars (findex f) const
Retrieve the variables adjacent to a factor in the factor graph.
void swap (factor_graph &gm)
Swap the contents of two factor graphs.
MER_ENUM (TreeType, WidthFirst, DepthFirst, MaxWeight)
Type of tree.
std::vector< edge_t > span_tree (TreeType tt, variable root)
Create a spanning tree of the factor graph.
std::vector< edge_t > span_tree (TreeType tt=TreeType::WidthFirst)
Create a spanning tree of the factor graph rooted by a randomly selected variable.
Public Member Functions inherited from merlin::graphical_model
graphical_model ()
Creates an empty graphical model.
graphical_model (const graphical_model &gm)
Creates a graphical model by copying an existing one.
graphical_model & operator= (const graphical_model &gm)
Assignment operator (deep copy).
graphical_model (std::vector< factor > fs)
Constructor from a list of factors.
template<class InputIterator >
graphical_model (InputIterator first, InputIterator last)
Creates a graphical model from input iterators.
virtual ~graphical_model ()
Destroys the graphical model.
void read (const char *file_name)
Read the graphical model from a file in the UAI format.
void write (const char *file_name)
Write the graphical model to a file using the UAI format.
bool is_markov ()
Check if graphical model is a Markov or a Bayes net.
std::vector< factor > assert_evidence (const char *file_name, std::map< size_t, size_t > &evidence, std::map< size_t, size_t > &old_to_new)
Assert evidence into the graphical model.
std::vector< factor > assert_evidence (const std::map< size_t, size_t > &evidence, std::map< size_t, size_t > &old_to_new)
Assert evidence into the graphical model.
size_t nvar () const
Return the number of variables in the model.
variable var (vindex i) const
Convert a variable index to Var object.
size_t num_factors () const
Return the number of factors in the model.
const factor & get_factor (findex idx) const
Accessor for a factor.
const std::vector< factor > & get_factors () const
Accessor for the factor container.
const flist & with_variable (const variable &v) const
Factors depending on a variable.
flist with_variable_set (const variable_set &vs) const
Union of factors depending on a set of variables.
flist intersects (const variable_set &vs) const
Intersection of factors depending on a set of variables.
flist contains (const variable &v) const
Factors depending on a variable.
flist contains (const variable_set &vs) const
Union of factors depending on a set of variables.
flist contained_by (const variable_set &vs) const
Factors contained by a set of variables.
variable_set markov_blanket (const variable &v) const
Markov blanket of a variable.
variable_set markov_blanket (const variable_set &vs) const
Markov blanket of a set of variables.
std::vector< variable_set > mrf () const
Full adjacency matrix.
void clear_factors ()
Remove all factors.
findex smallest (const flist &fl)
Find the factor with the smallest scope.
findex largest (const flist &fl)
Find the factor with the largest scope.
bool is_binary () const
Check if a binary model.
bool is_pairwise () const
Check if a pairwise model.
factor joint (size_t maxsize=0) const
Directly calculate joint distribution function.
size_t induced_width (const variable_order_t &order) const
Find the induced width (complexity) of an elimination order.
std::pair< size_t, size_t > pseudo_tree_size (const variable_order_t &order) const
Find induced width and pseudo tree height of an elimination order.
std::vector< vindex > pseudo_tree (const variable_order_t &order) const
Find the pseudo tree corresponding to an elimination order.
MER_ENUM (OrderMethod, MinFill, WtMinFill, MinWidth, WtMinWidth, Random)
Variable ordering methods.
variable_order_t order (OrderMethod ord_type) const
Find a variable elimination order.
variable_order_t order2 (OrderMethod ord_type) const
Find a variable elimination order.
variable_order_t order2 (OrderMethod ord_type, std::vector< bool > var_types) const
Find a constrained variable elimination order.
variable_order_t order (OrderMethod ord_type, std::vector< bool > var_types) const
Find a constrained variable elimination order.
void improve_order (OrderMethod ord_type, double &old_score, variable_order_t &old_order) const
Look for a better order iteratively.
void insert (std::vector< flist > &adj, findex idx, const variable_set &vs)
Add the scope of a factor to the adjacency list.
void erase (std::vector< flist > &adj, findex idx, const variable_set &vs)
Remove the scope of a factor from the adjacency list.
std::vector< size_t > max_simple ()
Find smallest factor with each variable and select its optimum.
std::vector< size_t > max_sequential (const variable_order_t &order)
Find maxmarginal for variable and select optimum given those so far.
double logP (const std::vector< size_t > &config)
Compute the log-probability of a particular (complete) configuration.
double get_global_const () const
Return the constant resulted from asserting evidence in the model.
Public Member Functions inherited from merlin::graph
graph (size_t n=0)
Constructs a graph with n vertices and 0 edges.
~graph ()
Destroys the graph.
index add_node ()
Add a node to the graph.
void remove_node (index i)
Remove a node from the graph.
size_t num_nodes ()
Return the number of nodes.
size_t num_edges ()
Return the number of edges.
const edge_id & add_edge (index i, index j)
Add an edge to the graph.
void remove_edge (index i, index j)
Remove an edge from the graph.
void clear ()
Clear the graph by removing all nodes and edges.
void clear_edges ()
Remove all edges.
const edge_id & edge (index i, index j) const
Return the edge (if any) between two nodes.
const set< edge_id > & neighbors (index i) const
Return the neighbors of a node (ie, adjacency list).
const edge_id & edge (index eij) const
Return an edge (by its index).
const std::vector< edge_id > & edges () const
Return the edges of the graph.
Protected Member Functions
double obj_entropy (size_t n)
Entropy computation.
void calc_belief (size_t n)
Belief computation.
void accept_incoming (size_t n)
Incoming messages computation.
void update_outgoing (size_t n)
Outgoing (new) messages computation.
Protected Member Functions inherited from merlin::factor_graph
flist _neighbors (findex i) const
Retrieve the neighbors of a factor.
void create_factor_graph ()
Create the factor graph.
eindex _eindex (findex i, findex j)
Retrieve the index of the edge between two nodes.
Protected Member Functions inherited from merlin::graphical_model
size_t _vindex (const variable &v) const
Look up the index of a variable.
flist & _with_variable (const variable &v)
Mutable accessor of adjacency.
void fixup ()
Internal function for ensuring consistency of the model.
double order_score (const std::vector< variable_set > &adj, size_t i, OrderMethod kOType) const
Compute the score of a variable for the elimination order.
variable_order_t order_random () const
Create a random elimination order.
Protected Attributes
std::vector< factor > m_beliefs
Store calculated messages and beliefs.
std::vector< factor > m_msg
Store messages.
std::vector< factor > m_msg_new
Store new messages.
indexed_heap m_priority
Store m_priority schedule of edges.
std::vector< findex > m_forder
Fixed order of factors.
Schedule m_sched
Schedule type.
factor::Distance m_dist
Message distance measure for priority_.
double m_log_z
Current objective function value.
bool m_debug
Internal debugging flag.
Protected Attributes inherited from merlin::algorithm
double m_stop_iter
Stopping criteria (iterations)
double m_stop_obj
Stopping criteria (objective change)
double m_stop_msg
Stopping criteria (message change)
double m_start_time
Start time.
Protected Attributes inherited from merlin::factor_graph
std::vector< size_t > m_vindex
Factors representing variable nodes in factor graph.
Protected Attributes inherited from merlin::graphical_model
std::vector< factor > m_factors
Collection of all factors in the model.
bool m_markov
Markov or Bayes network. Default is true (Markov)
Protected Attributes inherited from merlin::graph
std::stack< index > m_vvacant
List of available vertex ids.
std::stack< index > m_evacant
List of available edge ids.
Additional Inherited Members
Public Attributes inherited from merlin::graph
std::vector< set< edge_id > > m_adj
Look up EdgeID info by adj[i][jj] (jj = position of j).
std::vector< edge_id > m_edges
Look up EdgeID info by edges[eij] (edge index).
Protected Types inherited from merlin::factor_graph
typedef size_t eindex
Edge index.
Detailed Description
Loopy belief propagation over the factor graph.
Tasks supported: MAR
LBP propagates the messages along a factor graph representation of the original graphical model. It also computes an estimate of the partition function (it doesn't guarantee an upper or lower bound on Z).
Definition at line 47 of file lbp.h.
Constructor & Destructor Documentation
merlin::lbp::lbp (const factor_graph & fg) inline
Constructs algorithm instance from a copy of a factor graph.
Parameters
fg A factor graph
Definition at line 67 of file lbp.h.
References set_properties().
merlin::lbp::lbp (std::vector< factor > fs) inline
Constructs algorithm instance from a list of factors.
Parameters
fs A list of factors
Definition at line 75 of file lbp.h.
References set_properties().
template<class InputIterator > merlin::lbp::lbp (InputIterator f, InputIterator l) inline
Constructs algorithm instance from input iterators.
Parameters
f An iterator to beginning
l An iterator to end
Definition at line 85 of file lbp.h.
References set_properties().
Member Function Documentation
void merlin::lbp::accept_incoming (size_t n) inline protected
Incoming messages computation.
Accept all the incoming messages into a node, and recompute its belief.
Parameters
n The index of the node
Definition at line 476 of file lbp.h.
References merlin::set< T >::begin(), bel(), merlin::set< T >::end(), merlin::indexed_heap::erase(), merlin::graphical_model::get_factor(), merlin::graph::neighbors(), and merlin::factor::sum().
Referenced by run().
const factor& merlin::lbp::belief (size_t i) const inline virtual
Belief associated with a node of the graph.
Returns
the belief associated with a node of the graph. Nodes correspond typically to variables. The belied is a function represented by the Factor class.
Parameters
i The index of the node in the graph (from 0)
Implements merlin::algorithm.
Definition at line 105 of file lbp.h.
References m_beliefs.
Referenced by belief(), obj_entropy(), run(), update_outgoing(), and write_solution().
const factor& merlin::lbp::belief (variable v) const inline virtual
Belief associated with a particular variable.
Parameters
v The variable to compute the belief of
Returns
the belief associated with a particular variable in the graphical model. The belief is a function represented by the Factor class.
Implements merlin::algorithm.
Definition at line 108 of file lbp.h.
References belief(), and merlin::factor_graph::local_factor().
const factor& merlin::lbp::belief (variable_set vs) const inline virtual
Belief associated with a set of variables.
Parameters
vs The set of variables to compute the belief of
Returns
the belief associated with a set of variables in the graphical model. The belief is a function represented by the Factor class.
Implements merlin::algorithm.
Definition at line 111 of file lbp.h.
const std::vector<factor>& merlin::lbp::beliefs () const inline virtual
Beliefs associated with the variables.
Returns
the beliefs associated with the variables in the graphical model (one belief for each of the variables). The output vector is indexed by the same indexes used for the variables.
Implements merlin::algorithm.
Definition at line 114 of file lbp.h.
References m_beliefs.
std::vector<index> merlin::lbp::best_config () const inline virtual
Best configuration.
Returns
a vector containing the best configuration of the variables (i.e., variable value assignments) found so far. It is specific to optimization tasks (e.g., MAP, Marginal MAP).
Implements merlin::algorithm.
Definition at line 126 of file lbp.h.
void merlin::lbp::calc_belief (size_t n) inline protected
Belief computation.
Re-calculate the belief at a node from the current incoming messages.
Parameters
n The index of the node
Definition at line 462 of file lbp.h.
References merlin::set< T >::begin(), bel(), merlin::set< T >::end(), merlin::graph::neighbors(), and merlin::factor::sum().
virtual lbp* merlin::lbp::clone () const inline virtual
Clone the algorithm object.
Returns
the pointer to the object containing the cloned algorithm.
Implements merlin::algorithm.
Definition at line 93 of file lbp.h.
References lbp().
double merlin::lbp::lb () const inline virtual
Lower bound on the optimal value.
Returns
a lower bound on the optimal value defined by the inference task if available.
Implements merlin::algorithm.
Definition at line 120 of file lbp.h.
double merlin::lbp::logZ () const inline virtual
Log value of the partition function.
Returns
an estimate the log parition function. If the inference algorithm is an exact one then the return value is the exact log value of the partition function.
Implements merlin::algorithm.
Definition at line 132 of file lbp.h.
References m_log_z.
double merlin::lbp::logZlb () const inline virtual
Lower bound on the log partition function.
Returns
a lower bound on the log value of the parition function.
Implements merlin::algorithm.
Definition at line 138 of file lbp.h.
References MER_ENUM().
double merlin::lbp::logZub () const inline virtual
Upper bound on the log partition function.
Returns
an upper bound on the log value of the parition function. Most inference algorithms implemented in merlin support upper bounds on the log partition function.
Implements merlin::algorithm.
Definition at line 135 of file lbp.h.
double merlin::lbp::obj_entropy (size_t n) inline protected
Entropy computation.
Calculate the entropy contribution to the free energy from a node
Parameters
n The index of the node
Returns
the entropy contribution from node n.
Definition at line 446 of file lbp.h.
References merlin::factor_graph::adjacent_vars(), merlin::variable_set::begin(), belief(), merlin::variable_set::end(), merlin::factor::entropy(), merlin::factor_graph::is_var_node(), and merlin::factor::marginal().
Referenced by init(), and run().
void merlin::lbp::run () inline virtual
Run the algorithm.
Solves a probabilistic inference task.
Implements merlin::algorithm.
Definition at line 325 of file lbp.h.
References accept_incoming(), belief(), merlin::graph::edge(), merlin::graphical_model::get_factor(), init(), m_beliefs, m_debug, m_dist, m_forder, m_log_z, m_msg, m_msg_new, m_priority, m_sched, merlin::algorithm::m_start_time, merlin::algorithm::m_stop_iter, merlin::algorithm::m_stop_msg, merlin::algorithm::m_stop_obj, merlin::factor_graph::m_vindex, MERLIN_DOUBLE_PRECISION, merlin::graph::num_edges(), merlin::graphical_model::num_factors(), merlin::graphical_model::nvar(), obj_entropy(), merlin::indexed_heap::pop(), merlin::variable::states(), merlin::indexed_heap::top(), update_outgoing(), and merlin::graphical_model::var().
Referenced by Merlin::run().
virtual void merlin::lbp::set_properties (std::string opt = std::string()) inline virtual
Set the properties of the algorithm.
Parameters
opt The string containing comma separated property value pairs
Definition at line 156 of file lbp.h.
References m_debug, m_dist, m_sched, merlin::algorithm::set_stop_iter(), merlin::algorithm::set_stop_msg(), and merlin::algorithm::set_stop_obj().
Referenced by lbp(), and Merlin::run().
double merlin::lbp::ub () const inline virtual
Upper bound on the optimal value.
Returns
an upper bound on the optimal value defined by the inference task. It is specific to optimization tasks such as MAP and Marginal MAP inference.
Implements merlin::algorithm.
Definition at line 123 of file lbp.h.
void merlin::lbp::update_outgoing (size_t n) inline protected
Outgoing (new) messages computation.
Recompute new messages from node n to its neighbors.
Parameters
n The index of the node
Definition at line 496 of file lbp.h.
References merlin::set< T >::begin(), belief(), merlin::set< T >::end(), merlin::indexed_heap::insert(), merlin::graph::neighbors(), and merlin::factor::vars().
Referenced by run().
void merlin::lbp::write_solution (const char * file_name, const std::map< size_t, size_t > & evidence, const std::map< size_t, size_t > & old2new, const graphical_model & orig) inline
Write the solution to the output file.
Parameters
filename The output file name
evidence The evidence variable value pairs
old2new The mapping between old and new variable indexing
orig The graphical model prior to asserting evidence
Definition at line 285 of file lbp.h.
References belief(), m_log_z, MERLIN_DOUBLE_PRECISION, merlin::graphical_model::nvar(), merlin::variable::states(), and merlin::graphical_model::var().
Referenced by Merlin::run().
The documentation for this class was generated from the following file:
src/include/lbp.h