Merlin: merlin::graph Class Reference
merlin::graph Class Reference
The graph structure used by Merlin.
#include <graph.h>
Public Types
typedef edge_id::index index
Basic indexing type for the graph.
Public Member Functions
graph (size_t n=0)
Constructs a graph with n vertices and 0 edges.
~graph ()
Destroys the graph.
index add_node ()
Add a node to the graph.
void remove_node (index i)
Remove a node from the graph.
size_t num_nodes ()
Return the number of nodes.
size_t num_edges ()
Return the number of edges.
const edge_id & add_edge (index i, index j)
Add an edge to the graph.
void remove_edge (index i, index j)
Remove an edge from the graph.
void clear ()
Clear the graph by removing all nodes and edges.
void clear_edges ()
Remove all edges.
const edge_id & edge (index i, index j) const
Return the edge (if any) between two nodes.
const set< edge_id > & neighbors (index i) const
Return the neighbors of a node (ie, adjacency list).
const edge_id & edge (index eij) const
Return an edge (by its index).
const std::vector< edge_id > & edges () const
Return the edges of the graph.
Public Attributes
std::vector< set< edge_id > > m_adj
Look up EdgeID info by adj[i][jj] (jj = position of j).
std::vector< edge_id > m_edges
Look up EdgeID info by edges[eij] (edge index).
Protected Attributes
std::stack< index > m_vvacant
List of available vertex ids.
std::stack< index > m_evacant
List of available edge ids.
Detailed Description
The graph structure used by Merlin.
The graph contains N nodes (indexed 0..N-1) and E edges, with bidirectional indexing (0..2E-1).
Definition at line 106 of file graph.h.
Constructor & Destructor Documentation
merlin::graph::graph (size_t n = 0) inline explicit
Constructs a graph with n vertices and 0 edges.
Parameters
n The number of nodes
Definition at line 121 of file graph.h.
Member Function Documentation
const edge_id& merlin::graph::add_edge (index i, index j) inline
Add an edge to the graph.
Create the pairs (i,j) and (j,i) in the adjacency list.
Parameters
i The head of the edge
j The tail of the edge
Returns
the id (index) of the newly added edge.
Definition at line 176 of file graph.h.
References merlin::edge_id::edge_id(), and merlin::edge_id::NO_EDGE.
Referenced by merlin::factor_graph::add_factor(), merlin::factor_graph::create_factor_graph(), merlin::graphical_model::induced_width(), merlin::bte::init(), merlin::ijgp::init(), merlin::wmb::init(), merlin::graphical_model::order2(), and merlin::jglp::run().
index merlin::graph::add_node () inline
Add a node to the graph.
Returns
the index of the newly added node.
Definition at line 135 of file graph.h.
Referenced by merlin::graphical_model::add_factor(), and merlin::graphical_model::fixup().
const edge_id& merlin::graph::edge (index i, index j) const inline
Return the edge (if any) between two nodes.
Parameters
i The head of the edge
j The tail of the edge
Returns
the index of the edge if the edge is present or the static constant NO_EDGE if the edge is missing.
Definition at line 248 of file graph.h.
References merlin::edge_id::edge_id(), and merlin::edge_id::NO_EDGE.
Referenced by merlin::factor_graph::_eindex(), merlin::lbp::init(), merlin::graphical_model::order_score(), and merlin::lbp::run().
const edge_id& merlin::graph::edge (index eij) const inline
Return an edge (by its index).
Parameters
eij The index of the edge
Returns
the edge id corresponding to the index.
Definition at line 268 of file graph.h.
const std::vector<edge_id>& merlin::graph::edges () const inline
Return the edges of the graph.
Returns
the list of all edge ids in the graph.
Definition at line 276 of file graph.h.
Referenced by merlin::bte::init(), merlin::ijgp::init(), merlin::wmb::init(), and merlin::jglp::tighten().
const set<edge_id>& merlin::graph::neighbors (index i) const inline
Return the neighbors of a node (ie, adjacency list).
Parameters
i The index of the node
Returns
the set of edge ids that are adjacent to the node.
Definition at line 260 of file graph.h.
Referenced by merlin::factor_graph::_neighbors(), merlin::lbp::accept_incoming(), merlin::lbp::calc_belief(), merlin::graphical_model::induced_width(), merlin::lbp::init(), merlin::graphical_model::order2(), merlin::graphical_model::order_score(), merlin::factor_graph::span_tree(), and merlin::lbp::update_outgoing().
void merlin::graph::remove_edge (index i, index j) inline
Remove an edge from the graph.
Parameters
i The head of the edge to be removed
j The tail of the edge to be removed
Definition at line 210 of file graph.h.
References merlin::edge_id::idx, merlin::edge_id::NO_EDGE, and merlin::edge_id::ridx.
Referenced by merlin::graphical_model::order2(), and merlin::factor_graph::remove_factor().
void merlin::graph::remove_node (index i) inline
Remove a node from the graph.
Parameters
i Index of the node to be removed
Definition at line 150 of file graph.h.
Referenced by merlin::graphical_model::order2(), and merlin::graphical_model::remove_factor().
The documentation for this class was generated from the following file:
src/include/graph.h