Merlin: Merlin Class Reference
Merlin Class Reference
#include <merlin.h>
Public Member Functions
Merlin ()
Constructs the default Merlin engine.
~Merlin ()
Destroys the Merlin engine.
void set_algorithm (size_t alg)
Set the inference algorithm.
void set_task (size_t task)
Set the inference task.
void set_param_ibound (size_t ibound)
Set the i-bound.
void set_param_iterations (size_t iter)
Set the number of iterations.
void set_param_samples (size_t s)
Set the number of samples.
bool read_model (const char *file_name)
Read the graphical model from a file in the specified format.
bool read_evidence (const char *file_name)
Assert evidence.
bool read_query (const char *file_name)
Read the query variables (MMAP task only).
int run ()
Solve the inference task given current evidence.
bool write_model (const char *file_name)
Write the graphical model to a file in the specified format.
Protected Attributes
size_t m_task
Inference task (PR, MAR, MAP, MMAP).
size_t m_algorithm
Inference algorithm.
size_t m_param_ibound
Parameter: i-bound.
size_t m_param_iterations
Parameter: iterations.
size_t m_param_samples
Number of samples (Gibbs only)
Detailed Description
Merlin probabilistic inference engine.
Definition at line 66 of file merlin.h.
Member Function Documentation
bool Merlin::read_evidence (const char * filename)
Assert evidence.
Parameters
file_name The evidence file name.
Returns
true if successful and false otherwise.
Parameters
filename The evidence file name.
Definition at line 135 of file merlin.cpp.
bool Merlin::read_model (const char * filename)
Read the graphical model from a file in the specified format.
Read the graphical model.
Parameters
file_name The input file name.
file_format The input file format.
Returns
true if successful and false otherwise.
Parameters
filename The input file name.
Definition at line 110 of file merlin.cpp.
References merlin::graphical_model::clone(), and merlin::graphical_model::read().
bool Merlin::read_query (const char * filename)
Read the query variables (MMAP task only).
Parameters
file_name The query file name.
Returns
true if successful and false otherwise.
Parameters
filename The query file name.
Definition at line 171 of file merlin.cpp.
int Merlin::run ()
Solve the inference task given current evidence.
Returns
0 if succesful and 1 otherwise.
Definition at line 259 of file merlin.cpp.
References merlin::graphical_model::assert_evidence(), merlin::graphical_model::get_factors(), m_algorithm, m_param_ibound, m_param_iterations, m_param_samples, m_task, MERLIN_ALGO_BE, MERLIN_ALGO_GIBBS, MERLIN_ALGO_IJGP, MERLIN_ALGO_JGLP, MERLIN_ALGO_LBP, MERLIN_ALGO_WMB, MERLIN_TASK_MAP, MERLIN_TASK_MAR, MERLIN_TASK_MMAP, MERLIN_TASK_PR, merlin::graphical_model::nvar(), merlin::gibbs::run(), merlin::ijgp::run(), merlin::bte::run(), merlin::wmb::run(), merlin::lbp::run(), merlin::jglp::run(), merlin::gibbs::set_properties(), merlin::lbp::set_properties(), merlin::jglp::set_properties(), merlin::bte::set_properties(), merlin::ijgp::set_properties(), merlin::wmb::set_properties(), merlin::bte::set_query(), merlin::wmb::set_query(), merlin::bte::write_solution(), merlin::wmb::write_solution(), merlin::ijgp::write_solution(), merlin::lbp::write_solution(), merlin::gibbs::write_solution(), and merlin::jglp::write_solution().
void Merlin::set_algorithm (size_t alg)
Set the inference algorithm.
Parameters
alg The code associated with the algorithm.
Definition at line 70 of file merlin.cpp.
References m_algorithm.
void Merlin::set_param_ibound (size_t ibound)
Set the i-bound.
Parameters
ibound The value of the i-bound parameter.
Definition at line 86 of file merlin.cpp.
References m_param_ibound.
void Merlin::set_param_iterations (size_t iter)
Set the number of iterations.
Parameters
iter The number of iterations.
Definition at line 94 of file merlin.cpp.
References m_param_iterations.
void Merlin::set_param_samples (size_t s)
Set the number of samples.
Parameters
s The number of samples.
iter The number of samples.
Definition at line 102 of file merlin.cpp.
References m_param_samples.
void Merlin::set_task (size_t task)
Set the inference task.
Parameters
task The code associated with the task.
Definition at line 78 of file merlin.cpp.
References m_task.
bool Merlin::write_model (const char * filename)
Write the graphical model to a file in the specified format.
Write the graphical model.
Parameters
f The output file name.
format The file format supported.
Returns
true if successful and false otherwise.
Parameters
filename The output file name.
Definition at line 206 of file merlin.cpp.
References m_algorithm, m_task, MERLIN_ALGO_BE, MERLIN_ALGO_GIBBS, MERLIN_ALGO_IJGP, MERLIN_ALGO_JGLP, MERLIN_ALGO_LBP, MERLIN_ALGO_WMB, MERLIN_TASK_MAP, MERLIN_TASK_MAR, MERLIN_TASK_MMAP, MERLIN_TASK_PR, and merlin::graphical_model::write().
The documentation for this class was generated from the following files:
src/include/merlin.h
src/merlin.cpp