Merlin: merlin::ijgp Class Reference
merlin::ijgp Class Reference
#include <ijgp.h>
Classes
struct sPair
Helper class for pairs of sorted indices.
Public Types
typedef graphical_model::findex findex
Factor index.
typedef graphical_model::vindex vindex
Variable index.
typedef graphical_model::flist flist
Collection of factor indices.
Public Types inherited from merlin::graphical_model
typedef size_t findex
Factor index.
typedef size_t vindex
Variable index.
typedef set< findex > flist
Collection of factor indices.
Public Types inherited from merlin::graph
typedef edge_id::index index
Basic indexing type for the graph.
Public Member Functions
ijgp ()
Default constructor.
ijgp (const graphical_model &gm)
Constructor.
virtual ijgp * clone () const
Clone the model.
double ub () const
Upper bound on the optimal value.
double lb () const
Lower bound on the optimal value.
std::vector< size_t > best_config () const
Best configuration.
double logZ () const
Log value of the partition function.
double logZub () const
Upper bound on the log partition function.
double logZlb () const
Lower bound on the log partition function.
const factor & belief (size_t f) const
Belief associated with a node of the graph.
const factor & belief (variable v) const
Belief associated with a particular variable.
const factor & belief (variable_set vs) const
Belief associated with a set of variables.
const std::vector< factor > & beliefs () const
Beliefs associated with the variables.
const graphical_model & get_gm_orig () const
Access the original graphical model.
void write_solution (const char *file_name, const std::map< size_t, size_t > &evidence, const std::map< size_t, size_t > &old2new, const graphical_model &orig)
Write the solution to the output file.
virtual void run ()
Run the algorithm.
MER_ENUM (Task, PR, MAR, MAP)
Inference tasks supported.
MER_ENUM (Property, iBound, Order, Iter, Task, Debug)
Properties of the algorithm.
MER_ENUM (ElimOp, Max, Sum)
Elimination operators (sum, max).
void set_ibound (size_t i)
Set the i-bound parameter.
size_t get_ibound () const
Return the i-bound parameter.
void set_order (const variable_order_t &ord)
Set the variable elimination order.
void set_order_method (OrderMethod method)
Set the variable elimination order method.
const variable_order_t & get_order ()
Return the variable elimination order.
const std::vector< vindex > & get_pseudo_tree ()
Return the pseudo tree.
void set_pseudo_tree (const vector< vindex > &p)
Set the pseudo tree.
void set_graphical_model (const graphical_model &gm)
Set the graphical model content.
void set_graphical_model (const vector< factor > &fs)
Set the graphical model content from a list of factors.
virtual void set_properties (std::string opt=std::string())
Set the properties of the algorithm.
factor elim (const factor &F, const variable_set &vs)
Eliminate a set of variables from a factor.
factor marg (const factor &F, const variable_set &vs)
Compute the marginal over a set of variables.
double score (const vector< variable_set > &fin, const variable &VX, size_t i, size_t j)
Scoring function for bucket aggregation.
void init ()
Create the mini-bucket based join-graph (symbols only).
factor calc_belief (findex a)
Compute the belief of a cluster.
factor calc_belief (findex a, size_t b)
Compute the belief of a cluster excluding an incoming message.
factor incoming (findex a)
Compute the belief of a cluster excluding backward messages.
void forward ()
Forward (top-down) message passing.
void backward ()
Backward (bottom-up) message passing.
void update ()
Update the beliefs (marginals or max-marginals) for each variable.
void propagate (size_t nIter, double stopTime=-1, double stopObj=-1)
Iterative message passing over the join graph.
Public Member Functions inherited from merlin::graphical_model
graphical_model ()
Creates an empty graphical model.
graphical_model (const graphical_model &gm)
Creates a graphical model by copying an existing one.
graphical_model & operator= (const graphical_model &gm)
Assignment operator (deep copy).
virtual graphical_model * clone ()
Clone the graphical model.
graphical_model (std::vector< factor > fs)
Constructor from a list of factors.
template<class InputIterator >
graphical_model (InputIterator first, InputIterator last)
Creates a graphical model from input iterators.
virtual ~graphical_model ()
Destroys the graphical model.
void read (const char *file_name)
Read the graphical model from a file in the UAI format.
void write (const char *file_name)
Write the graphical model to a file using the UAI format.
bool is_markov ()
Check if graphical model is a Markov or a Bayes net.
std::vector< factor > assert_evidence (const char *file_name, std::map< size_t, size_t > &evidence, std::map< size_t, size_t > &old_to_new)
Assert evidence into the graphical model.
std::vector< factor > assert_evidence (const std::map< size_t, size_t > &evidence, std::map< size_t, size_t > &old_to_new)
Assert evidence into the graphical model.
size_t nvar () const
Return the number of variables in the model.
variable var (vindex i) const
Convert a variable index to Var object.
size_t num_factors () const
Return the number of factors in the model.
const factor & get_factor (findex idx) const
Accessor for a factor.
const std::vector< factor > & get_factors () const
Accessor for the factor container.
const flist & with_variable (const variable &v) const
Factors depending on a variable.
flist with_variable_set (const variable_set &vs) const
Union of factors depending on a set of variables.
flist intersects (const variable_set &vs) const
Intersection of factors depending on a set of variables.
flist contains (const variable &v) const
Factors depending on a variable.
flist contains (const variable_set &vs) const
Union of factors depending on a set of variables.
flist contained_by (const variable_set &vs) const
Factors contained by a set of variables.
variable_set markov_blanket (const variable &v) const
Markov blanket of a variable.
variable_set markov_blanket (const variable_set &vs) const
Markov blanket of a set of variables.
std::vector< variable_set > mrf () const
Full adjacency matrix.
virtual findex add_factor (const factor &F)
Add a new factor to the model.
virtual void remove_factor (findex idx)
Remove a factor from the model.
void clear_factors ()
Remove all factors.
findex smallest (const flist &fl)
Find the factor with the smallest scope.
findex largest (const flist &fl)
Find the factor with the largest scope.
bool is_binary () const
Check if a binary model.
bool is_pairwise () const
Check if a pairwise model.
factor joint (size_t maxsize=0) const
Directly calculate joint distribution function.
size_t induced_width (const variable_order_t &order) const
Find the induced width (complexity) of an elimination order.
std::pair< size_t, size_t > pseudo_tree_size (const variable_order_t &order) const
Find induced width and pseudo tree height of an elimination order.
std::vector< vindex > pseudo_tree (const variable_order_t &order) const
Find the pseudo tree corresponding to an elimination order.
MER_ENUM (OrderMethod, MinFill, WtMinFill, MinWidth, WtMinWidth, Random)
Variable ordering methods.
variable_order_t order (OrderMethod ord_type) const
Find a variable elimination order.
variable_order_t order2 (OrderMethod ord_type) const
Find a variable elimination order.
variable_order_t order2 (OrderMethod ord_type, std::vector< bool > var_types) const
Find a constrained variable elimination order.
variable_order_t order (OrderMethod ord_type, std::vector< bool > var_types) const
Find a constrained variable elimination order.
void improve_order (OrderMethod ord_type, double &old_score, variable_order_t &old_order) const
Look for a better order iteratively.
void insert (std::vector< flist > &adj, findex idx, const variable_set &vs)
Add the scope of a factor to the adjacency list.
void erase (std::vector< flist > &adj, findex idx, const variable_set &vs)
Remove the scope of a factor from the adjacency list.
std::vector< size_t > max_simple ()
Find smallest factor with each variable and select its optimum.
std::vector< size_t > max_sequential (const variable_order_t &order)
Find maxmarginal for variable and select optimum given those so far.
double logP (const std::vector< size_t > &config)
Compute the log-probability of a particular (complete) configuration.
double get_global_const () const
Return the constant resulted from asserting evidence in the model.
Public Member Functions inherited from merlin::graph
graph (size_t n=0)
Constructs a graph with n vertices and 0 edges.
~graph ()
Destroys the graph.
index add_node ()
Add a node to the graph.
void remove_node (index i)
Remove a node from the graph.
size_t num_nodes ()
Return the number of nodes.
size_t num_edges ()
Return the number of edges.
const edge_id & add_edge (index i, index j)
Add an edge to the graph.
void remove_edge (index i, index j)
Remove an edge from the graph.
void clear ()
Clear the graph by removing all nodes and edges.
void clear_edges ()
Remove all edges.
const edge_id & edge (index i, index j) const
Return the edge (if any) between two nodes.
const set< edge_id > & neighbors (index i) const
Return the neighbors of a node (ie, adjacency list).
const edge_id & edge (index eij) const
Return an edge (by its index).
const std::vector< edge_id > & edges () const
Return the edges of the graph.
Public Member Functions inherited from merlin::algorithm
algorithm ()
Constructs an empty algorithm.
virtual ~algorithm ()
Destructs the algorithm.
void set_stop_iter (double d)
Set the number of iterations.
void set_stop_obj (double d)
Set the minumum objective change before stopping.
void set_stop_msg (double d)
Set the minimum ammount a message changes before stopping.
Protected Attributes
graphical_model m_gmo
Original graphical model.
size_t num_iter
Number of iterations.
Task m_task
Inference task.
ElimOp m_elim_op
Elimination operator.
size_t m_ibound
i-bound parameter
double m_log_z
Log partition function value.
variable_order_t m_order
Variable elimination order.
OrderMethod m_order_method
Ordering method.
std::vector< vindex > m_parents
Pseudo tree.
std::vector< factor > m_beliefs
Marginals (or beliefs)
std::vector< size_t > m_best_config
MAP assignment.
double m_lb
Lower bound (ie, value of the MAP assignment)
Protected Attributes inherited from merlin::graphical_model
std::vector< factor > m_factors
Collection of all factors in the model.
bool m_markov
Markov or Bayes network. Default is true (Markov)
Protected Attributes inherited from merlin::graph
std::stack< index > m_vvacant
List of available vertex ids.
std::stack< index > m_evacant
List of available edge ids.
Protected Attributes inherited from merlin::algorithm
double m_stop_iter
Stopping criteria (iterations)
double m_stop_obj
Stopping criteria (objective change)
double m_stop_msg
Stopping criteria (message change)
double m_start_time
Start time.
Additional Inherited Members
Public Attributes inherited from merlin::graph
std::vector< set< edge_id > > m_adj
Look up EdgeID info by adj[i][jj] (jj = position of j).
std::vector< edge_id > m_edges
Look up EdgeID info by edges[eij] (edge index).
Protected Member Functions inherited from merlin::graphical_model
size_t _vindex (const variable &v) const
Look up the index of a variable.
flist & _with_variable (const variable &v)
Mutable accessor of adjacency.
void fixup ()
Internal function for ensuring consistency of the model.
double order_score (const std::vector< variable_set > &adj, size_t i, OrderMethod kOType) const
Compute the score of a variable for the elimination order.
variable_order_t order_random () const
Create a random elimination order.
Detailed Description
Iterative Join-Graph Propagation (IJGP)
Based on [Dechter and Mateescu, 2002] and [Marinescu, Kask and Dechter, 2003]
Tasks supported: MAR and MAP
IJGP is parameterized by an i-bound which limits the size of each cluster in the join-graph to at most i distict variables. Clearly IJGP(1) is equivalent with Loopy Belief Propagation, while IJGP(w*) is equivalent with the Join-Tree algorithm, hence exact.
The join-graph used by IJGP is obtained by running the mini-bucket algorithm schematically (ie, without computing the actual messages, only their scopes) and then connecting the mini-buckets residing in the same bucket. Messages are then propagated along the join-graph edges, following a top-down or bottom-up schedule.
Note that IJGP is only used for MAR (sum-prod) and MAP (max-prod) tasks. It doesn't compute an upper-bound (on the partition function, or the MAP value) because of overcounting. Therefore, logZ reported during the execution of the algorithm shouldn't be used as a valid measure for bounding (ignore). For valid bounding, use the WMB algorithm implemented in this library.
Definition at line 58 of file ijgp.h.
Member Function Documentation
const factor& merlin::ijgp::belief (size_t i) const inline virtual
Belief associated with a node of the graph.
Returns
the belief associated with a node of the graph. Nodes correspond typically to variables. The belied is a function represented by the Factor class.
Parameters
i The index of the node in the graph (from 0)
Implements merlin::algorithm.
Definition at line 112 of file ijgp.h.
References m_beliefs.
Referenced by run(), and write_solution().
const factor& merlin::ijgp::belief (variable v) const inline virtual
Belief associated with a particular variable.
Parameters
v The variable to compute the belief of
Returns
the belief associated with a particular variable in the graphical model. The belief is a function represented by the Factor class.
Implements merlin::algorithm.
Definition at line 115 of file ijgp.h.
References m_beliefs.
const factor& merlin::ijgp::belief (variable_set vs) const inline virtual
Belief associated with a set of variables.
Parameters
vs The set of variables to compute the belief of
Returns
the belief associated with a set of variables in the graphical model. The belief is a function represented by the Factor class.
Implements merlin::algorithm.
Definition at line 118 of file ijgp.h.
const std::vector<factor>& merlin::ijgp::beliefs () const inline virtual
Beliefs associated with the variables.
Returns
the beliefs associated with the variables in the graphical model (one belief for each of the variables). The output vector is indexed by the same indexes used for the variables.
Implements merlin::algorithm.
Definition at line 121 of file ijgp.h.
References m_beliefs.
std::vector<size_t> merlin::ijgp::best_config () const inline virtual
Best configuration.
Returns
a vector containing the best configuration of the variables (i.e., variable value assignments) found so far. It is specific to optimization tasks (e.g., MAP, Marginal MAP).
Implements merlin::algorithm.
Definition at line 98 of file ijgp.h.
References m_best_config.
factor merlin::ijgp::calc_belief (findex a) inline
Compute the belief of a cluster.
Parameters
a The index of the cluster
Returns
the factor representing the belief of the cluster.
Definition at line 820 of file ijgp.h.
References merlin::graphical_model::m_factors.
Referenced by backward(), forward(), and update().
factor merlin::ijgp::calc_belief (findex a, size_t b) inline
Compute the belief of a cluster excluding an incoming message.
Parameters
a The index of the cluster to compute the belief of
b The index of the cluster sending the incoming message
Returns
the factor representing the belief of cluster a excluding the incoming message from b to a.
Definition at line 850 of file ijgp.h.
References merlin::graphical_model::m_factors.
virtual ijgp* merlin::ijgp::clone () const inline virtual
Clone the model.
Returns
the pointer to the object containing the cloned model.
Implements merlin::algorithm.
Definition at line 85 of file ijgp.h.
References ijgp().
factor merlin::ijgp::elim (const factor & F, const variable_set & vs) inline
Eliminate a set of variables from a factor.
Parameters
F The reference of the factor to eliminate from
vs The set of variables to be eliminated
Returns
the factor resulted from eliminating the set of variables.
Definition at line 426 of file ijgp.h.
References merlin::factor::max(), and merlin::factor::sum().
Referenced by backward(), and forward().
factor merlin::ijgp::incoming (findex a) inline
Compute the belief of a cluster excluding backward messages.
Parameters
a The index of the cluster to compute the belief of
Returns
the factor representing the belief of cluster a excluding the backward messages from clusters below a.
Definition at line 881 of file ijgp.h.
References merlin::graphical_model::m_factors.
Referenced by update().
double merlin::ijgp::lb () const inline virtual
Lower bound on the optimal value.
Returns
a lower bound on the optimal value defined by the inference task if available.
Implements merlin::algorithm.
Definition at line 95 of file ijgp.h.
double merlin::ijgp::logZ () const inline virtual
Log value of the partition function.
Returns
an estimate the log parition function. If the inference algorithm is an exact one then the return value is the exact log value of the partition function.
Implements merlin::algorithm.
Definition at line 102 of file ijgp.h.
References m_log_z.
double merlin::ijgp::logZlb () const inline virtual
Lower bound on the log partition function.
Returns
a lower bound on the log value of the parition function.
Implements merlin::algorithm.
Definition at line 108 of file ijgp.h.
References m_log_z.
double merlin::ijgp::logZub () const inline virtual
Upper bound on the log partition function.
Returns
an upper bound on the log value of the parition function. Most inference algorithms implemented in merlin support upper bounds on the log partition function.
Implements merlin::algorithm.
Definition at line 105 of file ijgp.h.
References m_log_z.
factor merlin::ijgp::marg (const factor & F, const variable_set & vs) inline
Compute the marginal over a set of variables.
Parameters
F The reference of the factor to marginalize over
vs The set of variables representing the scope of the marginal
Returns
the factor representing the marginal over the set of variables.
Definition at line 444 of file ijgp.h.
References merlin::factor::marginal(), and merlin::factor::maxmarginal().
Referenced by update().
void merlin::ijgp::propagate (size_t nIter, double stopTime = -1, double stopObj = -1) inline
Iterative message passing over the join graph.
Parameters
nIter The number of iterations
stopTime The time limit
stopObj The error tolerance (ie, difference between objective values)
Definition at line 1070 of file ijgp.h.
References backward(), forward(), m_log_z, merlin::algorithm::m_start_time, MERLIN_DOUBLE_PRECISION, and update().
Referenced by run().
virtual void merlin::ijgp::run () inline virtual
Run the algorithm.
Solves a probabilistic inference task.
Implements merlin::algorithm.
Definition at line 204 of file ijgp.h.
References belief(), init(), merlin::graphical_model::logP(), m_best_config, m_gmo, m_lb, m_log_z, merlin::algorithm::m_start_time, m_task, MER_ENUM(), MERLIN_DOUBLE_PRECISION, num_iter, merlin::graphical_model::nvar(), propagate(), merlin::variable::states(), and merlin::graphical_model::var().
Referenced by Merlin::run().
double merlin::ijgp::score (const vector< variable_set > & fin, const variable & VX, size_t i, size_t j) inline
Scoring function for bucket aggregation.
Parameters
fin The set of factor scopes containing the pair (i,j) to be aggregated
VX The bucket variable
i The index of first scope
j The index of the second pair
Returns
the score that corresponds to aggregating the two scopes. It returns -3 if unable to combine, -1 for scope only aggregation, and otherwise a positive double score.
Definition at line 467 of file ijgp.h.
References merlin::variable_set::nvar().
Referenced by init().
void merlin::ijgp::set_graphical_model (const graphical_model & gm) inline
Set the graphical model content.
Parameters
gm The reference to the graphical model object
Definition at line 369 of file ijgp.h.
void merlin::ijgp::set_graphical_model (const vector< factor > & fs) inline
Set the graphical model content from a list of factors.
Parameters
fs The list of factors
Definition at line 377 of file ijgp.h.
References merlin::graphical_model::graphical_model().
void merlin::ijgp::set_ibound (size_t i) inline
Set the i-bound parameter.
Parameters
i The value of the i-bound (> 1)
Definition at line 315 of file ijgp.h.
Referenced by set_properties().
void merlin::ijgp::set_order (const variable_order_t & ord) inline
Set the variable elimination order.
Parameters
ord The variable order
Definition at line 330 of file ijgp.h.
void merlin::ijgp::set_order_method (OrderMethod method) inline
Set the variable elimination order method.
Parameters
method The elimination order method
Definition at line 338 of file ijgp.h.
virtual void merlin::ijgp::set_properties (std::string opt = std::string()) inline virtual
Set the properties of the algorithm.
Parameters
opt The string containing comma separated property value pairs
Definition at line 385 of file ijgp.h.
References set_ibound().
Referenced by ijgp(), and Merlin::run().
void merlin::ijgp::set_pseudo_tree (const vector< vindex > & p) inline
Set the pseudo tree.
Parameters
p The vector representing the pseudo tree
Definition at line 361 of file ijgp.h.
double merlin::ijgp::ub () const inline virtual
Upper bound on the optimal value.
Returns
an upper bound on the optimal value defined by the inference task. It is specific to optimization tasks such as MAP and Marginal MAP inference.
Implements merlin::algorithm.
Definition at line 92 of file ijgp.h.
void merlin::ijgp::write_solution (const char * file_name, const std::map< size_t, size_t > & evidence, const std::map< size_t, size_t > & old2new, const graphical_model & orig) inline
Write the solution to the output file.
Parameters
filename The output file name
evidence The evidence variable value pairs
old2new The mapping between old and new variable indexing
orig The graphical model prior to asserting evidence
Definition at line 139 of file ijgp.h.
References belief(), m_best_config, m_log_z, m_task, MERLIN_DOUBLE_PRECISION, merlin::graphical_model::nvar(), merlin::variable::states(), and merlin::graphical_model::var().
Referenced by Merlin::run().
The documentation for this class was generated from the following file:
src/include/ijgp.h