Merlin: merlin::factor_graph Class Reference
merlin::factor_graph Class Reference
A factor graph base class.
#include <factor_graph.h>
Classes
class abstract_queue
Queue type wrapper.
class abstract_queue_fifo
Queue type for breadth-first search.
class abstract_queue_lifo
Stack type for depth-first search.
Public Types
typedef graphical_model::findex findex
Factor index.
typedef graphical_model::vindex vindex
Variable index.
typedef graphical_model::flist flist
Collection of factor indices.
Public Types inherited from merlin::graphical_model
typedef size_t findex
Factor index.
typedef size_t vindex
Variable index.
typedef set< findex > flist
Collection of factor indices.
Public Types inherited from merlin::graph
typedef edge_id::index index
Basic indexing type for the graph.
Public Member Functions
factor_graph ()
Default constructor.
factor_graph (const factor_graph &fg)
Copy constructor.
factor_graph (std::vector< factor > fs)
Constructor.
template<class InputIterator >
factor_graph (InputIterator first, InputIterator last)
Constructor.
virtual factor_graph * clone ()
Clone the factor graph.
findex add_factor (const factor &F)
Add a new factor to the graphical model.
void remove_factor (findex f)
Remove a factor from the model.
findex local_factor (vindex i) const
Retrieve the factor index corresponding to a variable node.
findex local_factor (variable v) const
Retrieve the factor index corresponding to a variable node.
bool is_var_node (findex i) const
Check if a factor is a variable node in the factor graph.
flist adjacent_factors (variable v) const
Retrieve the factors adjacent to a variable node in the factor graph.
flist adjacent_factors (vindex v) const
Retrieve the factors adjacent to a variable node in the factor graph.
variable_set adjacent_vars (findex f) const
Retrieve the variables adjacent to a factor in the factor graph.
void swap (factor_graph &gm)
Swap the contents of two factor graphs.
MER_ENUM (TreeType, WidthFirst, DepthFirst, MaxWeight)
Type of tree.
std::vector< edge_t > span_tree (TreeType tt, variable root)
Create a spanning tree of the factor graph.
std::vector< edge_t > span_tree (TreeType tt=TreeType::WidthFirst)
Create a spanning tree of the factor graph rooted by a randomly selected variable.
Public Member Functions inherited from merlin::graphical_model
graphical_model ()
Creates an empty graphical model.
graphical_model (const graphical_model &gm)
Creates a graphical model by copying an existing one.
graphical_model & operator= (const graphical_model &gm)
Assignment operator (deep copy).
graphical_model (std::vector< factor > fs)
Constructor from a list of factors.
template<class InputIterator >
graphical_model (InputIterator first, InputIterator last)
Creates a graphical model from input iterators.
virtual ~graphical_model ()
Destroys the graphical model.
void read (const char *file_name)
Read the graphical model from a file in the UAI format.
void write (const char *file_name)
Write the graphical model to a file using the UAI format.
bool is_markov ()
Check if graphical model is a Markov or a Bayes net.
std::vector< factor > assert_evidence (const char *file_name, std::map< size_t, size_t > &evidence, std::map< size_t, size_t > &old_to_new)
Assert evidence into the graphical model.
std::vector< factor > assert_evidence (const std::map< size_t, size_t > &evidence, std::map< size_t, size_t > &old_to_new)
Assert evidence into the graphical model.
size_t nvar () const
Return the number of variables in the model.
variable var (vindex i) const
Convert a variable index to Var object.
size_t num_factors () const
Return the number of factors in the model.
const factor & get_factor (findex idx) const
Accessor for a factor.
const std::vector< factor > & get_factors () const
Accessor for the factor container.
const flist & with_variable (const variable &v) const
Factors depending on a variable.
flist with_variable_set (const variable_set &vs) const
Union of factors depending on a set of variables.
flist intersects (const variable_set &vs) const
Intersection of factors depending on a set of variables.
flist contains (const variable &v) const
Factors depending on a variable.
flist contains (const variable_set &vs) const
Union of factors depending on a set of variables.
flist contained_by (const variable_set &vs) const
Factors contained by a set of variables.
variable_set markov_blanket (const variable &v) const
Markov blanket of a variable.
variable_set markov_blanket (const variable_set &vs) const
Markov blanket of a set of variables.
std::vector< variable_set > mrf () const
Full adjacency matrix.
void clear_factors ()
Remove all factors.
findex smallest (const flist &fl)
Find the factor with the smallest scope.
findex largest (const flist &fl)
Find the factor with the largest scope.
bool is_binary () const
Check if a binary model.
bool is_pairwise () const
Check if a pairwise model.
factor joint (size_t maxsize=0) const
Directly calculate joint distribution function.
size_t induced_width (const variable_order_t &order) const
Find the induced width (complexity) of an elimination order.
std::pair< size_t, size_t > pseudo_tree_size (const variable_order_t &order) const
Find induced width and pseudo tree height of an elimination order.
std::vector< vindex > pseudo_tree (const variable_order_t &order) const
Find the pseudo tree corresponding to an elimination order.
MER_ENUM (OrderMethod, MinFill, WtMinFill, MinWidth, WtMinWidth, Random)
Variable ordering methods.
variable_order_t order (OrderMethod ord_type) const
Find a variable elimination order.
variable_order_t order2 (OrderMethod ord_type) const
Find a variable elimination order.
variable_order_t order2 (OrderMethod ord_type, std::vector< bool > var_types) const
Find a constrained variable elimination order.
variable_order_t order (OrderMethod ord_type, std::vector< bool > var_types) const
Find a constrained variable elimination order.
void improve_order (OrderMethod ord_type, double &old_score, variable_order_t &old_order) const
Look for a better order iteratively.
void insert (std::vector< flist > &adj, findex idx, const variable_set &vs)
Add the scope of a factor to the adjacency list.
void erase (std::vector< flist > &adj, findex idx, const variable_set &vs)
Remove the scope of a factor from the adjacency list.
std::vector< size_t > max_simple ()
Find smallest factor with each variable and select its optimum.
std::vector< size_t > max_sequential (const variable_order_t &order)
Find maxmarginal for variable and select optimum given those so far.
double logP (const std::vector< size_t > &config)
Compute the log-probability of a particular (complete) configuration.
double get_global_const () const
Return the constant resulted from asserting evidence in the model.
Public Member Functions inherited from merlin::graph
graph (size_t n=0)
Constructs a graph with n vertices and 0 edges.
~graph ()
Destroys the graph.
index add_node ()
Add a node to the graph.
void remove_node (index i)
Remove a node from the graph.
size_t num_nodes ()
Return the number of nodes.
size_t num_edges ()
Return the number of edges.
const edge_id & add_edge (index i, index j)
Add an edge to the graph.
void remove_edge (index i, index j)
Remove an edge from the graph.
void clear ()
Clear the graph by removing all nodes and edges.
void clear_edges ()
Remove all edges.
const edge_id & edge (index i, index j) const
Return the edge (if any) between two nodes.
const set< edge_id > & neighbors (index i) const
Return the neighbors of a node (ie, adjacency list).
const edge_id & edge (index eij) const
Return an edge (by its index).
const std::vector< edge_id > & edges () const
Return the edges of the graph.
Protected Types
typedef size_t eindex
Edge index.
Protected Member Functions
flist _neighbors (findex i) const
Retrieve the neighbors of a factor.
void create_factor_graph ()
Create the factor graph.
eindex _eindex (findex i, findex j)
Retrieve the index of the edge between two nodes.
Protected Member Functions inherited from merlin::graphical_model
size_t _vindex (const variable &v) const
Look up the index of a variable.
flist & _with_variable (const variable &v)
Mutable accessor of adjacency.
void fixup ()
Internal function for ensuring consistency of the model.
double order_score (const std::vector< variable_set > &adj, size_t i, OrderMethod kOType) const
Compute the score of a variable for the elimination order.
variable_order_t order_random () const
Create a random elimination order.
Protected Attributes
std::vector< size_t > m_vindex
Factors representing variable nodes in factor graph.
Protected Attributes inherited from merlin::graphical_model
std::vector< factor > m_factors
Collection of all factors in the model.
bool m_markov
Markov or Bayes network. Default is true (Markov)
Protected Attributes inherited from merlin::graph
std::stack< index > m_vvacant
List of available vertex ids.
std::stack< index > m_evacant
List of available edge ids.
Additional Inherited Members
Public Attributes inherited from merlin::graph
std::vector< set< edge_id > > m_adj
Look up EdgeID info by adj[i][jj] (jj = position of j).
std::vector< edge_id > m_edges
Look up EdgeID info by edges[eij] (edge index).
Detailed Description
A factor graph base class.
A graphical model represented as a bipartite graph between variable nodes, corresponding to the variables, and factor nodes, corresponding to the factors. Internally, factors and variables are mainly referenced by integer indices, with 0 <= f < nFactors() and 0 <= v < nvar(). However, many interface functions are called using a variable object, var(label,dim). To convert, var(v) gives the vth var object and the internal function _vindex(V) gives the index corresponding to variable object V.
Definition at line 44 of file factor_graph.h.
Constructor & Destructor Documentation
merlin::factor_graph::factor_graph (const factor_graph & fg) inline
Copy constructor.
Parameters
fg The factor graph to be copied
Definition at line 66 of file factor_graph.h.
merlin::factor_graph::factor_graph (std::vector< factor > fs) inline
Constructor.
Parameters
fs The list of factors
Definition at line 74 of file factor_graph.h.
References create_factor_graph(), m_vindex, and merlin::graphical_model::nvar().
template<class InputIterator > merlin::factor_graph::factor_graph (InputIterator first, InputIterator last) inline
Constructor.
Parameters
first The begin iterator of the factors list
last The end iterator of the factors list
Definition at line 85 of file factor_graph.h.
References create_factor_graph(), m_vindex, and merlin::graphical_model::nvar().
Member Function Documentation
eindex merlin::factor_graph::_eindex (findex i, findex j) inline protected
Retrieve the index of the edge between two nodes.
Parameters
i The (factor) index of the head
j The (factor) index of the tail
Returns
the index of the edge between the two factors.
Definition at line 269 of file factor_graph.h.
References merlin::graph::edge(), and merlin::edge_id::idx.
flist merlin::factor_graph::_neighbors (findex i) const inline protected
Retrieve the neighbors of a factor.
Parameters
i The index of the factor
Returns
the list of factor indexes that are connected to the input factor.
Definition at line 207 of file factor_graph.h.
References merlin::graph::neighbors().
Referenced by adjacent_factors().
findex merlin::factor_graph::add_factor (const factor & F) inline virtual
Add a new factor to the graphical model.
Parameters
F The factor to be added
Returns
the index of the newly added factor.
Reimplemented from merlin::graphical_model.
Definition at line 105 of file factor_graph.h.
References merlin::graph::add_edge(), merlin::graphical_model::add_factor(), merlin::variable_set::begin(), merlin::variable_set::end(), local_factor(), m_vindex, merlin::factor::nvar(), merlin::graphical_model::nvar(), and merlin::factor::vars().
flist merlin::factor_graph::adjacent_factors (variable v) const inline
Retrieve the factors adjacent to a variable node in the factor graph.
Parameters
v The index of the variable
Returns
the list of factor indexes corresponding to the adjacent factors.
Definition at line 170 of file factor_graph.h.
References _neighbors(), and local_factor().
flist merlin::factor_graph::adjacent_factors (vindex v) const inline
Retrieve the factors adjacent to a variable node in the factor graph.
Parameters
v The index of the variable
Returns
the list of factor indexes corresponding to the adjacent factors.
Definition at line 179 of file factor_graph.h.
References _neighbors(), and local_factor().
variable_set merlin::factor_graph::adjacent_vars (findex f) const inline
Retrieve the variables adjacent to a factor in the factor graph.
Parameters
f The index of the factor
Returns
the list of variable indexes corresponding to the adjacent variables.
Definition at line 188 of file factor_graph.h.
References merlin::graphical_model::get_factor(), swap(), and merlin::factor::vars().
Referenced by merlin::lbp::obj_entropy().
virtual factor_graph* merlin::factor_graph::clone () inline virtual
Clone the factor graph.
Returns
a pointer to the cloned factor graph.
Reimplemented from merlin::graphical_model.
Definition at line 95 of file factor_graph.h.
References factor_graph().
void merlin::factor_graph::create_factor_graph () inline protected
Create the factor graph.
Creates the bi-partite graph by adding nodes corresponding to local variable factors (ie, unary factors definded for each variable) and connecting them to the nodes corresponding to the factors. Let M be the number of factors. Then the nodes corresponding to the factors are indexed [0 .. M-1], while the nodes corresponding to the variables are indexed [M .. M+N-1] where N is the number of variables.
Definition at line 226 of file factor_graph.h.
References merlin::graphical_model::_vindex(), merlin::graph::add_edge(), merlin::graphical_model::add_factor(), is_var_node(), local_factor(), merlin::graphical_model::m_factors, m_vindex, merlin::graph::num_edges(), merlin::graphical_model::nvar(), and merlin::graphical_model::var().
Referenced by factor_graph().
bool merlin::factor_graph::is_var_node (findex i) const inline
Check if a factor is a variable node in the factor graph.
Parameters
i The index of the factor
Returns
true if the factor corresponds to a variable node, and false otherwise.
Definition at line 160 of file factor_graph.h.
References merlin::graphical_model::get_factor(), local_factor(), and merlin::graphical_model::nvar().
Referenced by create_factor_graph(), merlin::lbp::init(), merlin::lbp::obj_entropy(), and span_tree().
findex merlin::factor_graph::local_factor (vindex i) const inline
Retrieve the factor index corresponding to a variable node.
Parameters
i The index of a variable
Returns
the index of the factor associated with the variable in the factor graph.
Definition at line 140 of file factor_graph.h.
References m_vindex.
Referenced by add_factor(), adjacent_factors(), merlin::lbp::belief(), create_factor_graph(), is_var_node(), remove_factor(), and span_tree().
findex merlin::factor_graph::local_factor (variable v) const inline
Retrieve the factor index corresponding to a variable node.
Parameters
v The index of a variable
Returns
the index of the factor associated with the variable in the factor graph.
Definition at line 150 of file factor_graph.h.
References merlin::graphical_model::_vindex(), and m_vindex.
void merlin::factor_graph::remove_factor (findex f) inline virtual
Remove a factor from the model.
Parameters
f The index of the factor to be removed
Reimplemented from merlin::graphical_model.
Definition at line 124 of file factor_graph.h.
References merlin::graphical_model::_vindex(), merlin::variable_set::begin(), merlin::variable_set::end(), local_factor(), merlin::graphical_model::m_factors, m_vindex, merlin::graph::remove_edge(), and merlin::graphical_model::remove_factor().
std::vector<edge_t> merlin::factor_graph::span_tree (TreeType tt, variable root) inline
Create a spanning tree of the factor graph.
Parameters
tt The type of spanning tree
root The root (variable index) of the spanning tree
Returns
the spanning tree as a list of edge indexes in the factor graph.
Definition at line 344 of file factor_graph.h.
References merlin::graphical_model::_vindex(), merlin::set< T >::begin(), merlin::variable_set::begin(), merlin::set< T >::end(), merlin::variable_set::end(), merlin::graphical_model::get_factor(), is_var_node(), local_factor(), merlin::graph::neighbors(), merlin::graphical_model::num_factors(), merlin::graphical_model::nvar(), and merlin::factor::vars().
Referenced by span_tree().
std::vector<edge_t> merlin::factor_graph::span_tree (TreeType tt = TreeType::WidthFirst) inline
Create a spanning tree of the factor graph rooted by a randomly selected variable.
Parameters
tt The type of spanning tree
Returns
the spanning tree as a list of edge indexes in the factor graph.
Definition at line 408 of file factor_graph.h.
References merlin::graphical_model::nvar(), span_tree(), and merlin::graphical_model::var().
void merlin::factor_graph::swap (factor_graph & gm)
Swap the contents of two factor graphs.
Parameters
gm The factor graph to swap with
Referenced by adjacent_vars().
The documentation for this class was generated from the following file:
src/include/factor_graph.h